/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MessageDtoApiResponse } from '../../models/message-dto-api-response';

export interface ApiGroupsGroupIdMessagesMessageIdGet$Json$Params {

/**
 * Group ID
 */
  groupId: string;

/**
 * Message ID
 */
  messageId: string;
}

export function apiGroupsGroupIdMessagesMessageIdGet$Json(http: HttpClient, rootUrl: string, params: ApiGroupsGroupIdMessagesMessageIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<MessageDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiGroupsGroupIdMessagesMessageIdGet$Json.PATH, 'get');
  if (params) {
    rb.path('groupId', params.groupId, {});
    rb.path('messageId', params.messageId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MessageDtoApiResponse>;
    })
  );
}

apiGroupsGroupIdMessagesMessageIdGet$Json.PATH = '/api/groups/{groupId}/messages/{messageId}';
