/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MessageDtoIEnumerableApiResponse } from '../../models/message-dto-i-enumerable-api-response';

export interface ApiGroupsGroupIdMessagesGet$Plain$Params {

/**
 * Group ID
 */
  groupId: string;

/**
 * Get messages before this timestamp (ISO 8601)
 */
  before?: string;

/**
 * Maximum number of messages to return (1-100, default 20)
 */
  limit?: number;
}

export function apiGroupsGroupIdMessagesGet$Plain(http: HttpClient, rootUrl: string, params: ApiGroupsGroupIdMessagesGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<MessageDtoIEnumerableApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiGroupsGroupIdMessagesGet$Plain.PATH, 'get');
  if (params) {
    rb.path('groupId', params.groupId, {});
    rb.query('before', params.before, {});
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MessageDtoIEnumerableApiResponse>;
    })
  );
}

apiGroupsGroupIdMessagesGet$Plain.PATH = '/api/groups/{groupId}/messages';
