/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MessageDtoApiResponse } from '../../models/message-dto-api-response';
import { SendMessageDto } from '../../models/send-message-dto';

export interface ApiGroupsGroupIdMessagesPost$Json$Params {

/**
 * Group ID
 */
  groupId: string;
  
    /**
     * Message information
     */
    body?: SendMessageDto
}

export function apiGroupsGroupIdMessagesPost$Json(http: HttpClient, rootUrl: string, params: ApiGroupsGroupIdMessagesPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<MessageDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiGroupsGroupIdMessagesPost$Json.PATH, 'post');
  if (params) {
    rb.path('groupId', params.groupId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MessageDtoApiResponse>;
    })
  );
}

apiGroupsGroupIdMessagesPost$Json.PATH = '/api/groups/{groupId}/messages';
