/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MessageMetadataApiResponse } from '../../models/message-metadata-api-response';

export interface ApiMessagesMessageIdReadPost$Plain$Params {

/**
 * Message ID
 */
  messageId: string;
}

export function apiMessagesMessageIdReadPost$Plain(http: HttpClient, rootUrl: string, params: ApiMessagesMessageIdReadPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<MessageMetadataApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiMessagesMessageIdReadPost$Plain.PATH, 'post');
  if (params) {
    rb.path('messageId', params.messageId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MessageMetadataApiResponse>;
    })
  );
}

apiMessagesMessageIdReadPost$Plain.PATH = '/api/messages/{messageId}/read';
