/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GuidApiResponse } from '../../models/guid-api-response';

export interface ApiMessagesMessageIdForwardTargetGroupIdPost$Plain$Params {

/**
 * Original message ID
 */
  messageId: string;

/**
 * Target group ID
 */
  targetGroupId: string;
}

export function apiMessagesMessageIdForwardTargetGroupIdPost$Plain(http: HttpClient, rootUrl: string, params: ApiMessagesMessageIdForwardTargetGroupIdPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<GuidApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiMessagesMessageIdForwardTargetGroupIdPost$Plain.PATH, 'post');
  if (params) {
    rb.path('messageId', params.messageId, {});
    rb.path('targetGroupId', params.targetGroupId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GuidApiResponse>;
    })
  );
}

apiMessagesMessageIdForwardTargetGroupIdPost$Plain.PATH = '/api/messages/{messageId}/forward/{targetGroupId}';
