/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MessageMetadataApiResponse } from '../../models/message-metadata-api-response';

export interface ApiMessagesMessageIdReactionsEmojiPost$Json$Params {

/**
 * Message ID
 */
  messageId: string;

/**
 * Emoji reaction
 */
  emoji: string;
}

export function apiMessagesMessageIdReactionsEmojiPost$Json(http: HttpClient, rootUrl: string, params: ApiMessagesMessageIdReactionsEmojiPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<MessageMetadataApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiMessagesMessageIdReactionsEmojiPost$Json.PATH, 'post');
  if (params) {
    rb.path('messageId', params.messageId, {});
    rb.path('emoji', params.emoji, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MessageMetadataApiResponse>;
    })
  );
}

apiMessagesMessageIdReactionsEmojiPost$Json.PATH = '/api/messages/{messageId}/reactions/{emoji}';
