/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CatalogEntryDtoApiResponse } from '../../models/catalog-entry-dto-api-response';
import { UpsertCatalogEntryRequest } from '../../models/upsert-catalog-entry-request';

export interface ApiSettingsCatalogKeyPut$Plain$Params {

/**
 * Setting key
 */
  key: string;
  
    /**
     * Catalog entry request
     */
    body?: UpsertCatalogEntryRequest
}

export function apiSettingsCatalogKeyPut$Plain(http: HttpClient, rootUrl: string, params: ApiSettingsCatalogKeyPut$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<CatalogEntryDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiSettingsCatalogKeyPut$Plain.PATH, 'put');
  if (params) {
    rb.path('key', params.key, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CatalogEntryDtoApiResponse>;
    })
  );
}

apiSettingsCatalogKeyPut$Plain.PATH = '/api/settings/Catalog/{key}';
