/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CatalogEntryDtoApiResponse } from '../../models/catalog-entry-dto-api-response';

export interface ApiSettingsCatalogKeyGet$Json$Params {

/**
 * Setting key
 */
  key: string;
}

export function apiSettingsCatalogKeyGet$Json(http: HttpClient, rootUrl: string, params: ApiSettingsCatalogKeyGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<CatalogEntryDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiSettingsCatalogKeyGet$Json.PATH, 'get');
  if (params) {
    rb.path('key', params.key, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CatalogEntryDtoApiResponse>;
    })
  );
}

apiSettingsCatalogKeyGet$Json.PATH = '/api/settings/Catalog/{key}';
