/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CatalogResponseApiResponse } from '../../models/catalog-response-api-response';

export interface ApiSettingsCatalogGet$Plain$Params {

/**
 * Scope: 'public' (default) or 'admin'
 */
  scope?: string;

/**
 * Optional comma-separated list of categories
 */
  categories?: string;
}

export function apiSettingsCatalogGet$Plain(http: HttpClient, rootUrl: string, params?: ApiSettingsCatalogGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<CatalogResponseApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiSettingsCatalogGet$Plain.PATH, 'get');
  if (params) {
    rb.query('scope', params.scope, {});
    rb.query('categories', params.categories, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CatalogResponseApiResponse>;
    })
  );
}

apiSettingsCatalogGet$Plain.PATH = '/api/settings/Catalog';
