/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CatalogEntryDtoApiResponse } from '../../models/catalog-entry-dto-api-response';
import { UpsertCatalogEntryRequest } from '../../models/upsert-catalog-entry-request';

export interface ApiSettingsCatalogPost$Json$Params {
  
    /**
     * Catalog entry request
     */
    body?: UpsertCatalogEntryRequest
}

export function apiSettingsCatalogPost$Json(http: HttpClient, rootUrl: string, params?: ApiSettingsCatalogPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<CatalogEntryDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiSettingsCatalogPost$Json.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CatalogEntryDtoApiResponse>;
    })
  );
}

apiSettingsCatalogPost$Json.PATH = '/api/settings/Catalog';
