/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EffectiveThemeDtoApiResponse } from '../../models/effective-theme-dto-api-response';

export interface ApiThemesUserEffectiveGet$Params {

/**
 * Whether the system is in dark mode (optional, for sync behavior)
 */
  isDarkMode?: boolean;
}

export function apiThemesUserEffectiveGet(http: HttpClient, rootUrl: string, params?: ApiThemesUserEffectiveGet$Params, context?: HttpContext): Observable<StrictHttpResponse<EffectiveThemeDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiThemesUserEffectiveGet.PATH, 'get');
  if (params) {
    rb.query('isDarkMode', params.isDarkMode, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EffectiveThemeDtoApiResponse>;
    })
  );
}

apiThemesUserEffectiveGet.PATH = '/api/themes/user/effective';
