/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DynamicUserThemeDtoApiResponse } from '../../models/dynamic-user-theme-dto-api-response';
import { UpdateDynamicUserThemeDto } from '../../models/update-dynamic-user-theme-dto';

export interface ApiThemesUserPost$Params {
  
    /**
     * Updated theme preferences
     */
    body?: UpdateDynamicUserThemeDto
}

export function apiThemesUserPost(http: HttpClient, rootUrl: string, params?: ApiThemesUserPost$Params, context?: HttpContext): Observable<StrictHttpResponse<DynamicUserThemeDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiThemesUserPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DynamicUserThemeDtoApiResponse>;
    })
  );
}

apiThemesUserPost.PATH = '/api/themes/user';
