/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DynamicThemeDtoIEnumerableApiResponse } from '../../models/dynamic-theme-dto-i-enumerable-api-response';

export interface ApiThemesGet$Params {
}

export function apiThemesGet(http: HttpClient, rootUrl: string, params?: ApiThemesGet$Params, context?: HttpContext): Observable<StrictHttpResponse<DynamicThemeDtoIEnumerableApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiThemesGet.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DynamicThemeDtoIEnumerableApiResponse>;
    })
  );
}

apiThemesGet.PATH = '/api/themes';
