/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DynamicThemeDtoApiResponse } from '../../models/dynamic-theme-dto-api-response';

export interface ApiThemesThemeIdGet$Params {

/**
 * Theme ID
 */
  themeId: string;
}

export function apiThemesThemeIdGet(http: HttpClient, rootUrl: string, params: ApiThemesThemeIdGet$Params, context?: HttpContext): Observable<StrictHttpResponse<DynamicThemeDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiThemesThemeIdGet.PATH, 'get');
  if (params) {
    rb.path('themeId', params.themeId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DynamicThemeDtoApiResponse>;
    })
  );
}

apiThemesThemeIdGet.PATH = '/api/themes/{themeId}';
