/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PollResultsDtoApiResponse } from '../../models/poll-results-dto-api-response';
import { VotePollDto } from '../../models/vote-poll-dto';

export interface ApiGroupsGroupIdMessagesMessageIdPollsVotePost$Json$Params {

/**
 * Group ID
 */
  groupId: string;

/**
 * Message ID containing the poll
 */
  messageId: string;
  
    /**
     * Vote data
     */
    body?: VotePollDto
}

export function apiGroupsGroupIdMessagesMessageIdPollsVotePost$Json(http: HttpClient, rootUrl: string, params: ApiGroupsGroupIdMessagesMessageIdPollsVotePost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<PollResultsDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiGroupsGroupIdMessagesMessageIdPollsVotePost$Json.PATH, 'post');
  if (params) {
    rb.path('groupId', params.groupId, {});
    rb.path('messageId', params.messageId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PollResultsDtoApiResponse>;
    })
  );
}

apiGroupsGroupIdMessagesMessageIdPollsVotePost$Json.PATH = '/api/groups/{groupId}/messages/{messageId}/polls/vote';
