/**
 * TaskFlow Chat API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GroupRole } from './groupRole';


export interface GroupMemberDto { 
    memberId?: string;
    groupId?: string;
    userId?: string | null;
    userName?: string | null;
    fullName?: string | null;
    role?: GroupRole;
    joinedAt?: string;
}
export namespace GroupMemberDto {
}


