/**
 * TaskFlow Chat API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MessageDto } from './messageDto';


export interface GroupDto { 
    groupId?: string;
    name?: string | null;
    inviteCode?: string | null;
    inviteLink?: string | null;
    createdAt?: string;
    createdBy?: string | null;
    isPublic?: boolean;
    memberCount?: number;
    lastMessage?: MessageDto;
}

