/**
 * TaskFlow Chat API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const GroupRole = {
    NUMBER_0: 0,
    NUMBER_1: 1
} as const;
export type GroupRole = typeof GroupRole[keyof typeof GroupRole];

