/**
 * TaskFlow Chat API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MessageMetadata { 
    forwardCount?: number;
    originalMessageId?: string | null;
    reactions?: { [key: string]: string; } | null;
    deliveredTo?: { [key: string]: string; } | null;
    readBy?: { [key: string]: string; } | null;
}

