/**
 * TaskFlow Chat API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ObjectApiResponse { 
    success?: boolean;
    data?: any | null;
    message?: string | null;
    errorCode?: string | null;
    details?: any | null;
    traceId?: string | null;
}

