/**
 * TaskFlow Chat API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserDto { 
    id?: string | null;
    userName?: string | null;
    email?: string | null;
    fullName?: string | null;
    createdAt?: string;
    roles?: Array<string> | null;
}

