/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EffectiveSettingsResponseApiResponse } from '../../models/effective-settings-response-api-response';

export interface ApiSettingsMeGet$Plain$Params {

/**
 * Optional comma-separated list of categories to retrieve
 */
  categories?: string;
}

export function apiSettingsMeGet$Plain(http: HttpClient, rootUrl: string, params?: ApiSettingsMeGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<EffectiveSettingsResponseApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiSettingsMeGet$Plain.PATH, 'get');
  if (params) {
    rb.query('categories', params.categories, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EffectiveSettingsResponseApiResponse>;
    })
  );
}

apiSettingsMeGet$Plain.PATH = '/api/Settings/me';
