/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ValidateSettingsRequest } from '../../models/validate-settings-request';
import { ValidationResponseApiResponse } from '../../models/validation-response-api-response';

export interface ApiSettingsMeValidatePost$Json$Params {
  
    /**
     * Validation request
     */
    body?: ValidateSettingsRequest
}

export function apiSettingsMeValidatePost$Json(http: HttpClient, rootUrl: string, params?: ApiSettingsMeValidatePost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ValidationResponseApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiSettingsMeValidatePost$Json.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ValidationResponseApiResponse>;
    })
  );
}

apiSettingsMeValidatePost$Json.PATH = '/api/Settings/me/validate';
