/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SettingsDtoApiResponse } from '../../models/settings-dto-api-response';
import { UpdateSettingsRequest } from '../../models/update-settings-request';

export interface ApiSettingsMePut$Json$Params {
  
    /**
     * Settings update request
     */
    body?: UpdateSettingsRequest
}

export function apiSettingsMePut$Json(http: HttpClient, rootUrl: string, params?: ApiSettingsMePut$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<SettingsDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiSettingsMePut$Json.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SettingsDtoApiResponse>;
    })
  );
}

apiSettingsMePut$Json.PATH = '/api/Settings/me';
