/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FlatTranslationDtoApiResponse } from '../../models/flat-translation-dto-api-response';
import { UpdateTranslationRequest } from '../../models/update-translation-request';

export interface ApiAdminI18NKeyLocalePut$Json$Params {

/**
 * Translation key (URL encoded)
 */
  key: string;

/**
 * Locale/language code
 */
  locale: string;
  
    /**
     * Update request
     */
    body?: UpdateTranslationRequest
}

export function apiAdminI18NKeyLocalePut$Json(http: HttpClient, rootUrl: string, params: ApiAdminI18NKeyLocalePut$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<FlatTranslationDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiAdminI18NKeyLocalePut$Json.PATH, 'put');
  if (params) {
    rb.path('key', params.key, {});
    rb.path('locale', params.locale, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FlatTranslationDtoApiResponse>;
    })
  );
}

apiAdminI18NKeyLocalePut$Json.PATH = '/api/admin/i18n/{key}/{locale}';
