/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BulkUpsertRequest } from '../../models/bulk-upsert-request';
import { SeedResultDtoApiResponse } from '../../models/seed-result-dto-api-response';

export interface ApiAdminI18NBulkUpsertPost$Json$Params {
  
    /**
     * Bulk upsert request with translations
     */
    body?: BulkUpsertRequest
}

export function apiAdminI18NBulkUpsertPost$Json(http: HttpClient, rootUrl: string, params?: ApiAdminI18NBulkUpsertPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<SeedResultDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiAdminI18NBulkUpsertPost$Json.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SeedResultDtoApiResponse>;
    })
  );
}

apiAdminI18NBulkUpsertPost$Json.PATH = '/api/admin/i18n/bulk-upsert';
