/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SeedResultDtoApiResponse } from '../../models/seed-result-dto-api-response';

export interface ApiAdminI18NSeedFilePost$Json$Params {
      body?: {
'file'?: Blob;
}
}

export function apiAdminI18NSeedFilePost$Json(http: HttpClient, rootUrl: string, params?: ApiAdminI18NSeedFilePost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<SeedResultDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiAdminI18NSeedFilePost$Json.PATH, 'post');
  if (params) {
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SeedResultDtoApiResponse>;
    })
  );
}

apiAdminI18NSeedFilePost$Json.PATH = '/api/admin/i18n/seed/file';
