/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponse } from '../../models/api-response';
import { ObjectApiResponse } from '../../models/object-api-response';

export interface ApiAdminI18NKeyLocaleDelete$Plain$Params {

/**
 * Translation key (URL encoded)
 */
  key: string;

/**
 * Locale/language code
 */
  locale: string;
}

export function apiAdminI18NKeyLocaleDelete$Plain(http: HttpClient, rootUrl: string, params: ApiAdminI18NKeyLocaleDelete$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<(ObjectApiResponse | ApiResponse)>> {
  const rb = new RequestBuilder(rootUrl, apiAdminI18NKeyLocaleDelete$Plain.PATH, 'delete');
  if (params) {
    rb.path('key', params.key, {});
    rb.path('locale', params.locale, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<(ObjectApiResponse | ApiResponse)>;
    })
  );
}

apiAdminI18NKeyLocaleDelete$Plain.PATH = '/api/admin/i18n/{key}/{locale}';
