/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ClearCacheResultDtoApiResponse } from '../../models/clear-cache-result-dto-api-response';

export interface ApiAdminI18NClearCachePost$Json$Params {

/**
 * Specific locale to clear (optional, clears all if not specified)
 */
  locale?: string;
}

export function apiAdminI18NClearCachePost$Json(http: HttpClient, rootUrl: string, params?: ApiAdminI18NClearCachePost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ClearCacheResultDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiAdminI18NClearCachePost$Json.PATH, 'post');
  if (params) {
    rb.query('locale', params.locale, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ClearCacheResultDtoApiResponse>;
    })
  );
}

apiAdminI18NClearCachePost$Json.PATH = '/api/admin/i18n/clear-cache';
