/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LanguageDto } from '../../models/language-dto';
import { LanguageDtoApiResponse } from '../../models/language-dto-api-response';

export interface ApiAdminI18NLanguagesPost$Json$Params {
  
    /**
     * Language data
     */
    body?: LanguageDto
}

export function apiAdminI18NLanguagesPost$Json(http: HttpClient, rootUrl: string, params?: ApiAdminI18NLanguagesPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<LanguageDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiAdminI18NLanguagesPost$Json.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<LanguageDtoApiResponse>;
    })
  );
}

apiAdminI18NLanguagesPost$Json.PATH = '/api/admin/i18n/languages';
