/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponse } from '../../models/api-response';
import { ObjectApiResponse } from '../../models/object-api-response';

export interface ApiAdminI18NChangesGet$Json$Params {

/**
 * Filter by locale
 */
  locale?: string;

/**
 * Filter by category
 */
  category?: string;

/**
 * Filter from date
 */
  fromDate?: string;

/**
 * Filter to date
 */
  toDate?: string;

/**
 * Page number
 */
  page?: number;

/**
 * Page size
 */
  pageSize?: number;
}

export function apiAdminI18NChangesGet$Json(http: HttpClient, rootUrl: string, params?: ApiAdminI18NChangesGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<(ObjectApiResponse | ApiResponse)>> {
  const rb = new RequestBuilder(rootUrl, apiAdminI18NChangesGet$Json.PATH, 'get');
  if (params) {
    rb.query('locale', params.locale, {});
    rb.query('category', params.category, {});
    rb.query('fromDate', params.fromDate, {});
    rb.query('toDate', params.toDate, {});
    rb.query('page', params.page, {});
    rb.query('pageSize', params.pageSize, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<(ObjectApiResponse | ApiResponse)>;
    })
  );
}

apiAdminI18NChangesGet$Json.PATH = '/api/admin/i18n/changes';
