/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Injectable } from '@angular/core';
import { AppConfigService } from '../core/services/app-config.service';

/**
 * Global configuration
 */
@Injectable({
  providedIn: 'root',
})
export class ApiConfiguration {
  private _rootUrl?: string;

  constructor(private appConfigService: AppConfigService) {}

  /**
   * Returns the root url for API operations.
   * Uses runtime configuration from AppConfigService if not explicitly set.
   * Always returns a valid URL, never undefined.
   */
  get rootUrl(): string {
    if (this._rootUrl) {
      return this._rootUrl;
    }
    
    const apiUrl = this.appConfigService.getApiUrl();
    
    // Double-check we have a valid URL
    if (!apiUrl) {
      console.error('ApiConfiguration: getApiUrl returned null/undefined, using fallback');
      return 'https://localhost:44347';
    }
    
    return apiUrl;
  }

  /**
   * Sets the root URL for API operations.
   */
  set rootUrl(rootUrl: string) {
    this._rootUrl = rootUrl;
  }
}

/**
 * Parameters for `ApiModule.forRoot()`
 */
export interface ApiConfigurationParams {
  rootUrl?: string;
}
