/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { AuthService } from './services/auth.service';
import { CatalogService } from './services/catalog.service';
import { EmailProviderAdminService } from './services/email-provider-admin.service';
import { GroupsService } from './services/groups.service';
import { HealthService } from './services/health.service';
import { I18NService } from './services/i-18-n.service';
import { I18NAdminService } from './services/i-18-n-admin.service';
import { MessageMetadataService } from './services/message-metadata.service';
import { MessagesService } from './services/messages.service';
import { PollsService } from './services/polls.service';
import { SettingsService } from './services/settings.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    AuthService,
    CatalogService,
    EmailProviderAdminService,
    GroupsService,
    HealthService,
    I18NService,
    I18NAdminService,
    MessageMetadataService,
    MessagesService,
    PollsService,
    SettingsService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
