/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { InjectionToken } from '@angular/core';

/**
 * Injection token for the API base path
 */
export const BASE_PATH = new InjectionToken<string>('basePath');