/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { I18NMetadataDtoApiResponse } from '../../models/i-18-n-metadata-dto-api-response';

export interface ApiI18NMetadataGet$Json$Params {
}

export function apiI18NMetadataGet$Json(http: HttpClient, rootUrl: string, params?: ApiI18NMetadataGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<I18NMetadataDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiI18NMetadataGet$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<I18NMetadataDtoApiResponse>;
    })
  );
}

apiI18NMetadataGet$Json.PATH = '/api/i18n/metadata';
