/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TranslationPayloadDtoApiResponse } from '../../models/translation-payload-dto-api-response';

export interface ApiI18NLangKeysGet$Plain$Params {

/**
 * Language code
 */
  lang: string;

/**
 * Comma-separated list of translation keys
 */
  keys?: string;

/**
 * Output format: "flat" (default) or "nested"
 */
  format?: string;
}

export function apiI18NLangKeysGet$Plain(http: HttpClient, rootUrl: string, params: ApiI18NLangKeysGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<TranslationPayloadDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiI18NLangKeysGet$Plain.PATH, 'get');
  if (params) {
    rb.path('lang', params.lang, {});
    rb.query('keys', params.keys, {});
    rb.query('format', params.format, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TranslationPayloadDtoApiResponse>;
    })
  );
}

apiI18NLangKeysGet$Plain.PATH = '/api/i18n/{lang}/keys';
