/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TranslationSearchResultDtoApiResponse } from '../../models/translation-search-result-dto-api-response';

export interface ApiI18NLangSearchGet$Plain$Params {

/**
 * Language code
 */
  lang: string;

/**
 * Search query (searches in keys and values)
 */
  q?: string;

/**
 * Optional category filter
 */
  category?: string;

/**
 * Page number (default: 1)
 */
  page?: number;

/**
 * Results per page (default: 50, max: 100)
 */
  pageSize?: number;
}

export function apiI18NLangSearchGet$Plain(http: HttpClient, rootUrl: string, params: ApiI18NLangSearchGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<TranslationSearchResultDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiI18NLangSearchGet$Plain.PATH, 'get');
  if (params) {
    rb.path('lang', params.lang, {});
    rb.query('q', params.q, {});
    rb.query('category', params.category, {});
    rb.query('page', params.page, {});
    rb.query('pageSize', params.pageSize, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TranslationSearchResultDtoApiResponse>;
    })
  );
}

apiI18NLangSearchGet$Plain.PATH = '/api/i18n/{lang}/search';
