/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TranslationPayloadDtoApiResponse } from '../../models/translation-payload-dto-api-response';

export interface ApiI18NLangGet$Json$Params {

/**
 * Language code (e.g., "en", "hi", "ar")
 */
  lang: string;

/**
 * Output format: "nested" (default) or "flat"
 */
  format?: string;

/**
 * Optional version for cache busting
 */
  version?: string;
}

export function apiI18NLangGet$Json(http: HttpClient, rootUrl: string, params: ApiI18NLangGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<TranslationPayloadDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiI18NLangGet$Json.PATH, 'get');
  if (params) {
    rb.path('lang', params.lang, {});
    rb.query('format', params.format, {});
    rb.query('version', params.version, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TranslationPayloadDtoApiResponse>;
    })
  );
}

apiI18NLangGet$Json.PATH = '/api/i18n/{lang}';
