/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GroupDtoApiResponse } from '../../models/group-dto-api-response';

export interface ApiGroupsJoinInviteCodePost$Plain$Params {

/**
 * Invite code
 */
  inviteCode: string;
}

export function apiGroupsJoinInviteCodePost$Plain(http: HttpClient, rootUrl: string, params: ApiGroupsJoinInviteCodePost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<GroupDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiGroupsJoinInviteCodePost$Plain.PATH, 'post');
  if (params) {
    rb.path('inviteCode', params.inviteCode, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GroupDtoApiResponse>;
    })
  );
}

apiGroupsJoinInviteCodePost$Plain.PATH = '/api/Groups/join/{inviteCode}';
