/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GroupDtoApiResponse } from '../../models/group-dto-api-response';

export interface ApiGroupsIdSummaryGet$Plain$Params {

/**
 * Group ID
 */
  id: string;
}

export function apiGroupsIdSummaryGet$Plain(http: HttpClient, rootUrl: string, params: ApiGroupsIdSummaryGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<GroupDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiGroupsIdSummaryGet$Plain.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GroupDtoApiResponse>;
    })
  );
}

apiGroupsIdSummaryGet$Plain.PATH = '/api/Groups/{id}/summary';
