/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GroupDtoIEnumerableApiResponse } from '../../models/group-dto-i-enumerable-api-response';

export interface ApiGroupsGet$Json$Params {
}

export function apiGroupsGet$Json(http: HttpClient, rootUrl: string, params?: ApiGroupsGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<GroupDtoIEnumerableApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiGroupsGet$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GroupDtoIEnumerableApiResponse>;
    })
  );
}

apiGroupsGet$Json.PATH = '/api/Groups';
