/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GroupDtoApiResponse } from '../../models/group-dto-api-response';
import { UpdateGroupNameDto } from '../../models/update-group-name-dto';

export interface ApiGroupsIdNamePut$Plain$Params {

/**
 * Group ID
 */
  id: string;
  
    /**
     * Update information
     */
    body?: UpdateGroupNameDto
}

export function apiGroupsIdNamePut$Plain(http: HttpClient, rootUrl: string, params: ApiGroupsIdNamePut$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<GroupDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiGroupsIdNamePut$Plain.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GroupDtoApiResponse>;
    })
  );
}

apiGroupsIdNamePut$Plain.PATH = '/api/Groups/{id}/name';
