/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GroupDtoIEnumerableApiResponse } from '../../models/group-dto-i-enumerable-api-response';

export interface ApiGroupsRecentGet$Plain$Params {

/**
 * Maximum number of groups to return (default 10)
 */
  limit?: number;
}

export function apiGroupsRecentGet$Plain(http: HttpClient, rootUrl: string, params?: ApiGroupsRecentGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<GroupDtoIEnumerableApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiGroupsRecentGet$Plain.PATH, 'get');
  if (params) {
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GroupDtoIEnumerableApiResponse>;
    })
  );
}

apiGroupsRecentGet$Plain.PATH = '/api/Groups/recent';
