/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PresenceDtoIEnumerableApiResponse } from '../../models/presence-dto-i-enumerable-api-response';

export interface ApiGroupsIdPresenceGet$Json$Params {

/**
 * Group ID
 */
  id: string;
}

export function apiGroupsIdPresenceGet$Json(http: HttpClient, rootUrl: string, params: ApiGroupsIdPresenceGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<PresenceDtoIEnumerableApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiGroupsIdPresenceGet$Json.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PresenceDtoIEnumerableApiResponse>;
    })
  );
}

apiGroupsIdPresenceGet$Json.PATH = '/api/Groups/{id}/presence';
