/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponse } from '../../models/api-response';
import { ObjectApiResponse } from '../../models/object-api-response';

export interface ApiGroupsSearchGet$Json$Params {

/**
 * Search term for group name
 */
  search?: string;

/**
 * Page number (1-based, default 1)
 */
  page?: number;

/**
 * Page size (default 20, max 100)
 */
  pageSize?: number;
}

export function apiGroupsSearchGet$Json(http: HttpClient, rootUrl: string, params?: ApiGroupsSearchGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<(ObjectApiResponse | ApiResponse)>> {
  const rb = new RequestBuilder(rootUrl, apiGroupsSearchGet$Json.PATH, 'get');
  if (params) {
    rb.query('search', params.search, {});
    rb.query('page', params.page, {});
    rb.query('pageSize', params.pageSize, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<(ObjectApiResponse | ApiResponse)>;
    })
  );
}

apiGroupsSearchGet$Json.PATH = '/api/Groups/search';
