/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GroupDtoApiResponse } from '../../models/group-dto-api-response';
import { UpdateVisibilityDto } from '../../models/update-visibility-dto';

export interface ApiGroupsIdVisibilityPut$Json$Params {

/**
 * Group ID
 */
  id: string;
  
    /**
     * Update information
     */
    body?: UpdateVisibilityDto
}

export function apiGroupsIdVisibilityPut$Json(http: HttpClient, rootUrl: string, params: ApiGroupsIdVisibilityPut$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<GroupDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiGroupsIdVisibilityPut$Json.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GroupDtoApiResponse>;
    })
  );
}

apiGroupsIdVisibilityPut$Json.PATH = '/api/Groups/{id}/visibility';
