/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EmailProviderDtoApiResponse } from '../../models/email-provider-dto-api-response';
import { UpdateEmailProviderDto } from '../../models/update-email-provider-dto';

export interface ApiAdminEmailProvidersIdPut$Plain$Params {

/**
 * Provider ID
 */
  id: string;
  
    /**
     * Updated provider details
     */
    body?: UpdateEmailProviderDto
}

export function apiAdminEmailProvidersIdPut$Plain(http: HttpClient, rootUrl: string, params: ApiAdminEmailProvidersIdPut$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<EmailProviderDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiAdminEmailProvidersIdPut$Plain.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EmailProviderDtoApiResponse>;
    })
  );
}

apiAdminEmailProvidersIdPut$Plain.PATH = '/api/admin/email-providers/{id}';
