/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EmailProviderDtoApiResponse } from '../../models/email-provider-dto-api-response';

export interface ApiAdminEmailProvidersIdGet$Json$Params {

/**
 * Provider ID
 */
  id: string;
}

export function apiAdminEmailProvidersIdGet$Json(http: HttpClient, rootUrl: string, params: ApiAdminEmailProvidersIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<EmailProviderDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiAdminEmailProvidersIdGet$Json.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EmailProviderDtoApiResponse>;
    })
  );
}

apiAdminEmailProvidersIdGet$Json.PATH = '/api/admin/email-providers/{id}';
