/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CreateEmailProviderDto } from '../../models/create-email-provider-dto';
import { EmailProviderDtoApiResponse } from '../../models/email-provider-dto-api-response';

export interface ApiAdminEmailProvidersPost$Json$Params {
  
    /**
     * Email provider details
     */
    body?: CreateEmailProviderDto
}

export function apiAdminEmailProvidersPost$Json(http: HttpClient, rootUrl: string, params?: ApiAdminEmailProvidersPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<EmailProviderDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiAdminEmailProvidersPost$Json.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EmailProviderDtoApiResponse>;
    })
  );
}

apiAdminEmailProvidersPost$Json.PATH = '/api/admin/email-providers';
