/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponse } from '../../models/api-response';
import { ObjectApiResponse } from '../../models/object-api-response';

export interface ApiAdminEmailProvidersIdDelete$Plain$Params {

/**
 * Provider ID
 */
  id: string;
}

export function apiAdminEmailProvidersIdDelete$Plain(http: HttpClient, rootUrl: string, params: ApiAdminEmailProvidersIdDelete$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<(ObjectApiResponse | ApiResponse)>> {
  const rb = new RequestBuilder(rootUrl, apiAdminEmailProvidersIdDelete$Plain.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<(ObjectApiResponse | ApiResponse)>;
    })
  );
}

apiAdminEmailProvidersIdDelete$Plain.PATH = '/api/admin/email-providers/{id}';
