/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ObjectApiResponse } from '../models/object-api-response';

/**
 * Standardized API response without data
 */
export type ApiResponse = ObjectApiResponse & {
};
