/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FileContent } from '../models/file-content';

/**
 * Audio message content (extends FileContent)
 */
export type AudioContent = FileContent & {

/**
 * Duration of the audio in seconds
 */
'durationSeconds'?: number;
} & {

/**
 * Type discriminator (always 'audio' for AudioContent)
 */
'$type': string;
};
