/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Request DTO for bulk translation upsert
 */
export interface BulkUpsertTranslationDto {

  /**
   * Category key (optional, will be derived from key if not provided)
   */
  categoryKey?: string | null;

  /**
   * Context/notes for translators (optional)
   */
  context?: string | null;

  /**
   * Translation key
   */
  key: string;

  /**
   * Locale/language code
   */
  locale: string;

  /**
   * Source text (optional)
   */
  sourceText?: string | null;

  /**
   * Translated value
   */
  value: string;
}
