/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CatalogEntryDto } from '../models/catalog-entry-dto';
import { SettingsI18N } from '../models/settings-i-18-n';

/**
 * Category with its keys
 */
export interface CategoryWithKeys {
  adminOnly?: boolean;
  beta?: boolean;
  deprecated?: boolean;
  description?: string | null;
  displayName?: string;

  /**
   * Represents internationalization (i18n) keys for settings entities.
   * Contains mappings for field translations and option-specific translations.
   */
  i18n?: SettingsI18N | null;
  icon?: string | null;
  iconColor?: string | null;
  iconSelected?: string | null;
  key?: string;
  keys?: Array<CatalogEntryDto>;
  markdownDescription?: string | null;
  order?: number;
  sectionDivider?: boolean;
  sidebarGroup?: string | null;
}
