/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * DTO for complete theme configuration (base theme + accent colors combined)
 * This represents the final theme that the frontend will apply
 */
export interface CompleteThemeDto {

  /**
   * Accent variant ID
   */
  accentId?: string;

  /**
   * Primary background color (hex format)
   */
  backgroundColor?: string;

  /**
   * Badge background color (hex format)
   */
  badgeColor?: string;

  /**
   * Border color for UI elements (hex format)
   */
  borderColor?: string;

  /**
   * Error/danger color (hex format)
   */
  errorColor?: string;

  /**
   * Icon color that complements the accent (hex format)
   */
  iconColor?: string;

  /**
   * Whether this is a dark theme
   */
  isDarkTheme?: boolean;

  /**
   * Complete theme name (e.g., "Light - Blue", "Dark - Green")
   */
  name?: string;

  /**
   * Primary accent color for buttons, links, highlights (hex format)
   */
  primaryAccentColor?: string;

  /**
   * Secondary accent color for hover states, secondary buttons (hex format)
   */
  secondaryAccentColor?: string;

  /**
   * Secondary background color for containers/cards (hex format)
   */
  secondaryBackgroundColor?: string;

  /**
   * Secondary text color for less prominent text (hex format)
   */
  secondaryTextColor?: string;

  /**
   * Success color (hex format)
   */
  successColor?: string;

  /**
   * Primary text color (hex format)
   */
  textColor?: string;

  /**
   * Base theme ID
   */
  themeId?: string;

  /**
   * Warning color (hex format)
   */
  warningColor?: string;
}
