/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * DTO for email provider
 */
export interface EmailProviderDto {
  createdAt?: string;
  enableSsl?: boolean;
  failureCount?: number;
  fromEmail?: string | null;
  fromName?: string | null;
  host?: string | null;
  id?: string;
  isActive?: boolean;
  isDefault?: boolean;
  lastFailureReason?: string | null;
  lastUsedAt?: string | null;
  port?: number;
  priority?: number;
  providerName?: string;
  providerType?: string;
  rateLimitPerHour?: number;
  rateLimitPerMinute?: number;
  senderEmail?: string | null;
  timeoutSeconds?: number;
  updatedAt?: string;
}
