/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MessageContent } from '../models/message-content';

/**
 * File message content
 */
export type FileContent = MessageContent & {

/**
 * URL to the file
 */
'url'?: string;

/**
 * Original file name
 */
'fileName'?: string;

/**
 * File size in bytes
 */
'fileSize'?: number;

/**
 * MIME type of the file
 */
'mimeType'?: string;
} & {
'$type': 'file';

/**
 * Type discriminator (always 'file' for FileContent)
 */
'$type': string;
};
