/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * DTO for forgot password request
 */
export interface ForgotPasswordDto {

  /**
   * User's email address
   */
  email?: string;
}
