/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MessageDto } from '../models/message-dto';

/**
 * DTO for group information
 */
export interface GroupDto {

  /**
   * Date and time when the group was created
   */
  createdAt?: string;

  /**
   * ID of the user who created the group
   */
  createdBy?: string;

  /**
   * Group ID
   */
  groupId?: string;

  /**
   * Invite code for joining the group
   */
  inviteCode?: string;

  /**
   * Invite link for joining the group
   */
  inviteLink?: string;

  /**
   * Whether the group is publicly visible
   */
  isPublic?: boolean;

  /**
   * Last message sent in the group, if any
   */
  lastMessage?: MessageDto | null;

  /**
   * Number of members in the group
   */
  memberCount?: number;

  /**
   * Name of the group
   */
  name?: string;
}
