/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { I18NMetadataDto } from '../models/i-18-n-metadata-dto';

/**
 * Standardized API response wrapper
 */
export interface I18NMetadataDtoApiResponse {

  /**
   * The response data (only present on success)
   */
  data?: I18NMetadataDto | null;

  /**
   * Additional error details (only present on failure and in non-production environments)
   */
  details?: any | null;

  /**
   * Error code (only present on failure)
   */
  errorCode?: string | null;

  /**
   * Optional human-readable message (present on success or failure)
   */
  message?: string | null;

  /**
   * Indicates if the request was successful
   */
  success?: boolean;

  /**
   * Trace ID for correlating logs
   */
  traceId?: string | null;
}
