/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * DTO for joining a group
 */
export interface JoinGroupDto {

  /**
   * Invite code for the group
   */
  inviteCode?: string;
}
