/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * DTO for user login
 */
export interface LoginDto {

  /**
   * Password
   */
  password?: string;

  /**
   * Username or email
   */
  userName?: string;
}
