/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Message metadata containing additional information
 */
export interface MessageMetadata {

  /**
   * Users who have received delivery confirmation along with timestamp
   */
  deliveredTo?: {
[key: string]: string | null;
};

  /**
   * Number of times this message has been forwarded
   */
  forwardCount?: number | null;

  /**
   * ID of the original message if this is a forwarded/reply message
   */
  originalMessageId?: string | null;

  /**
   * Reactions to the message (userId -> emoji)
   */
  reactions?: {
[key: string]: string | null;
};

  /**
   * Users who have read the message along with timestamp
   */
  readBy?: {
[key: string]: string | null;
};

  /**
   * ID of the message this message is replying to
   */
  replyToMessageId?: string | null;
}
