/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ImageContent } from '../models/image-content';
import { PollContent } from '../models/poll-content';
import { TextContent } from '../models/text-content';
import { VideoContent } from '../models/video-content';

/**
 * Base class for message content
 */
export type MessageContent = (TextContent | ImageContent | VideoContent | PollContent);
