/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ImageContent } from '../models/image-content';
import { MessageMetadata } from '../models/message-metadata';
import { PollContent } from '../models/poll-content';
import { TextContent } from '../models/text-content';
import { VideoContent } from '../models/video-content';

/**
 * DTO for message information
 */
export interface MessageDto {

  /**
   * Base class for message content
   */
  content?: (TextContent | ImageContent | VideoContent | PollContent);

  /**
   * Represents the content type of a message
   */
  contentType?: 'text' | 'image' | 'video' | 'poll';

  /**
   * Date and time when the message was created
   */
  createdAt?: string;

  /**
   * Group ID
   */
  groupId?: string;

  /**
   * Message ID
   */
  messageId?: string;

  /**
   * Represents the type of message (flattened into clear user + system types)
   */
  messageType?: 'userMessage' | 'userJoined' | 'userLeft' | 'groupCreated' | 'groupUpdated' | 'groupDeleted' | 'memberRoleChanged' | 'inviteCodeRegenerated';

  /**
   * Message metadata containing additional information
   */
  metadata?: MessageMetadata;

  /**
   * ID of the user who sent the message
   */
  senderId?: string;

  /**
   * Name of the user who sent the message
   */
  senderName?: string;

  /**
   * Represents the source type of a message
   */
  sourceType?: 'user' | 'system';
}
