/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Poll message content - immutable value object.
 * Represents interactive polls with multiple options.
 */
export interface PollContent {

  /**
   * Discriminator (always 'poll')
   */
  contentType: string;
}
