/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * DTO for user presence information in a group
 */
export interface PresenceDto {

  /**
   * Number of active connections for this user
   */
  connectionCount?: number;

  /**
   * Online status of the user
   */
  isOnline?: boolean;

  /**
   * Last seen timestamp (if offline)
   */
  lastSeen?: string | null;

  /**
   * User ID
   */
  userId?: string;

  /**
   * User display name
   */
  userName?: string;
}
