/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * DTO for refresh token request
 */
export interface RefreshTokenDto {

  /**
   * Refresh token
   */
  refreshToken?: string;
}
