/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * DTO for user registration
 */
export interface RegisterDto {

  /**
   * Email address for the new user
   */
  email?: string;

  /**
   * Full name of the user (optional)
   */
  fullName?: string | null;

  /**
   * Password for the new user
   */
  password?: string;

  /**
   * Username for the new user
   */
  userName?: string;
}
