/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * DTO for revoking a specific session
 */
export interface RevokeSessionDto {

  /**
   * Session ID to revoke
   */
  sessionId?: string;
}
