/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Error entry for seed operations
 */
export interface SeedError {

  /**
   * Error message
   */
  error?: string;

  /**
   * Translation key that caused the error
   */
  key?: string;

  /**
   * Locale associated with the error (if applicable)
   */
  locale?: string | null;
}
