/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SeedFileMeta } from '../models/seed-file-meta';

/**
 * Seed file format for importing translations
 */
export interface SeedFileDto {

  /**
   * Nested translation data
   */
  data?: {
[key: string]: any;
};

  /**
   * Metadata about the language
   */
  meta?: SeedFileMeta;
}
