/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GeneralFileContent } from '../models/general-file-content';
import { ImageContent } from '../models/image-content';
import { MessageMetadata } from '../models/message-metadata';
import { PollContent } from '../models/poll-content';
import { TextContent } from '../models/text-content';
import { VideoContent } from '../models/video-content';

/**
 * DTO for sending a message
 */
export interface SendMessageDto {

  /**
   * Base abstract class for all message content types.
   * Serves as a discriminated union for WhatsApp-style polymorphic message content.
   */
  content: (TextContent | GeneralFileContent | ImageContent | VideoContent | PollContent);

  /**
   * Represents the content type of a message
   */
  contentType?: 'text' | 'image' | 'video' | 'poll';

  /**
   * Represents the type of message (flattened into clear user + system types)
   */
  messageType?: 'userMessage' | 'userJoined' | 'userLeft' | 'groupCreated' | 'groupUpdated' | 'groupDeleted' | 'memberRoleChanged' | 'inviteCodeRegenerated';

  /**
   * Message metadata containing additional information
   */
  metadata?: MessageMetadata | null;
}
