/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AudioContent } from '../models/audio-content';
import { FileContent } from '../models/file-content';
import { ImageContent } from '../models/image-content';
import { MessageMetadata } from '../models/message-metadata';
import { PollContent } from '../models/poll-content';
import { TextContent } from '../models/text-content';
import { VideoContent } from '../models/video-content';

/**
 * DTO for sending a message
 */
export interface SendMessageDto {

  /**
   * Base class for message content
   */
  content: (TextContent | FileContent | ImageContent | AudioContent | VideoContent | PollContent);

  /**
   * Represents the content type of a message
   */
  contentType?: 'text' | 'file' | 'image' | 'audio' | 'video' | 'poll';

  /**
   * Represents the type of message (flattened into clear user + system types)
   */
  messageType?: 'userMessage' | 'userJoined' | 'userLeft' | 'groupCreated' | 'groupUpdated' | 'groupDeleted' | 'memberRoleChanged' | 'inviteCodeRegenerated';

  /**
   * Message metadata containing additional information
   */
  metadata?: MessageMetadata | null;
}
