/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { VisibilityCondition } from '../models/visibility-condition';

/**
 * UI configuration for a setting
 */
export interface SettingUiConfig {

  /**
   * Whether this setting is only visible to admins
   */
  adminOnly?: boolean;

  /**
   * Control width: full, half, third
   */
  controlWidth?: string | null;

  /**
   * Display order within the category
   */
  order?: number;

  /**
   * Conditional visibility rules
   */
  visibleWhen?: Array<VisibilityCondition> | null;
}
