/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Represents an option for select/radio/multiselect fields
 */
export interface SettingOption {

  /**
   * Bootstrap icon name for this option (e.g., "sun", "moon", "laptop")
   */
  icon?: string | null;

  /**
   * Display label for this option
   */
  label?: string;

  /**
   * Additional metadata for this option
   */
  meta?: ({
[key: string]: any;
}) | null;

  /**
   * The value to be stored
   */
  value?: string;
}
