/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Validation rules for a setting
 */
export interface SettingValidation {

  /**
   * Allowed values for select/radio fields
   */
  allowedValues?: Array<string> | null;

  /**
   * JSON Schema for object-type fields
   */
  jsonSchema?: string | null;

  /**
   * Maximum value for numeric fields
   */
  max?: number | null;

  /**
   * Maximum length for string fields
   */
  maxLength?: number | null;

  /**
   * Minimum value for numeric fields
   */
  min?: number | null;

  /**
   * Regular expression pattern for text validation
   */
  regex?: string | null;
}
