/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Validation error for a specific setting key
 */
export interface SettingValidationError {
  code?: string;
  key?: string;
  message?: string;
}
