/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ThemeAccentDto } from '../models/theme-accent-dto';

/**
 * DTO for base theme information
 */
export interface ThemeDto {

  /**
   * Available accent color variants for this base theme
   */
  accentVariants?: Array<ThemeAccentDto>;

  /**
   * Primary background color (hex format)
   */
  backgroundColor?: string;

  /**
   * Border color for UI elements (hex format)
   */
  borderColor?: string;

  /**
   * Theme ID
   */
  id?: string;

  /**
   * Whether this theme is built-in
   */
  isBuiltIn?: boolean;

  /**
   * Whether this is a dark theme
   */
  isDarkTheme?: boolean;

  /**
   * Base theme name (Light/Dark)
   */
  name?: string;

  /**
   * Secondary background color for containers/cards (hex format)
   */
  secondaryBackgroundColor?: string;

  /**
   * Secondary text color for less prominent text (hex format)
   */
  secondaryTextColor?: string;

  /**
   * Primary text color (hex format)
   */
  textColor?: string;
}
