/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * DTO for theme information
 */
export interface ThemeDto {

  /**
   * Primary background color (hex format)
   */
  backgroundColor?: string;

  /**
   * Border color for UI elements (hex format)
   */
  borderColor?: string;

  /**
   * Error/danger color (hex format)
   */
  errorColor?: string;

  /**
   * Primary highlight/accent color (hex format)
   */
  highlightColor?: string;

  /**
   * Primary icon color (hex format)
   */
  iconColor?: string;

  /**
   * Theme ID
   */
  id?: string;

  /**
   * Whether this theme is built-in
   */
  isBuiltIn?: boolean;

  /**
   * Whether this is a dark theme
   */
  isDarkTheme?: boolean;

  /**
   * Display name of the theme
   */
  name?: string;

  /**
   * Secondary background color for containers/cards (hex format)
   */
  secondaryBackgroundColor?: string;

  /**
   * Secondary text color for less prominent text (hex format)
   */
  secondaryTextColor?: string;

  /**
   * Success color (hex format)
   */
  successColor?: string;

  /**
   * Primary text color (hex format)
   */
  textColor?: string;

  /**
   * Warning color (hex format)
   */
  warningColor?: string;
}
