/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Translation category metadata DTO
 */
export interface TranslationCategoryDto {

  /**
   * Description
   */
  description?: string | null;

  /**
   * Display name
   */
  displayName?: string;

  /**
   * Category key
   */
  key?: string;

  /**
   * Number of translation keys in this category
   */
  keyCount?: number;
}
