/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Metadata for translation payload
 */
export interface TranslationPayloadMeta {

  /**
   * Timestamp when this payload was generated
   */
  generatedAt?: string;

  /**
   * Language code (e.g., "en", "hi")
   */
  lang?: string;

  /**
   * Total number of translation keys
   */
  totalKeys?: number;

  /**
   * Version string for cache invalidation
   */
  version?: string;
}
