/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * DTO for updating a group's visibility
 */
export interface UpdateVisibilityDto {

  /**
   * Visibility setting for the group ("Public" or "Private")
   */
  visibility?: string;
}
