/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * DTO for updating user theme preferences
 */
export interface UpdateDynamicUserThemeDto {

  /**
   * Selected Dark Theme ID
   */
  darkThemeId?: string | null;

  /**
   * Selected Dark Theme Variant ID
   */
  darkVariantId?: string | null;

  /**
   * Selected Light Theme ID
   */
  lightThemeId?: string | null;

  /**
   * Selected Light Theme Variant ID
   */
  lightVariantId?: string | null;

  /**
   * Whether to sync with system settings
   */
  syncWithSystem?: boolean | null;
}
