/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Request to update user settings
 */
export interface UpdateSettingsRequest {
  category?: string;
  payload?: {
[key: string]: any;
};
}
