/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * DTO for updating a group's name
 */
export interface UpdateGroupNameDto {

  /**
   * New name for the group
   */
  name?: string;
}
