/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * DTO for updating user theme sync preferences
 */
export interface UpdateThemeSyncDto {

  /**
   * Whether to sync with system settings
   */
  syncWithSystem: boolean;
}
