/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * DTO for updating an existing email provider
 */
export interface UpdateEmailProviderDto {

  /**
   * OAuth2 Client ID (for Gmail API providers) - only provide if changing
   */
  clientId?: string | null;

  /**
   * OAuth2 Client Secret (for Gmail API providers) - only provide if changing
   */
  clientSecret?: string | null;

  /**
   * Whether to use SSL/TLS
   */
  enableSsl?: boolean | null;

  /**
   * Default from email address
   */
  fromEmail?: string | null;

  /**
   * Default from display name
   */
  fromName?: string | null;

  /**
   * SMTP host (for SMTP providers)
   */
  host?: string | null;

  /**
   * Whether this provider is active
   */
  isActive?: boolean | null;

  /**
   * Whether this is the default provider
   */
  isDefault?: boolean | null;

  /**
   * SMTP password (will be encrypted, for SMTP providers) - only provide if changing
   */
  password?: string | null;

  /**
   * SMTP port (for SMTP providers)
   */
  port?: number | null;

  /**
   * Priority/weight for load balancing (higher = more traffic)
   */
  priority?: number | null;

  /**
   * Provider name (e.g., "Gmail API Production", "SMTP Backup")
   */
  providerName?: string | null;

  /**
   * Rate limit per hour
   */
  rateLimitPerHour?: number | null;

  /**
   * Rate limit per minute
   */
  rateLimitPerMinute?: number | null;

  /**
   * OAuth2 Refresh Token (for Gmail API providers) - only provide if changing
   */
  refreshToken?: string | null;

  /**
   * Sender email address
   */
  senderEmail?: string | null;

  /**
   * Timeout in seconds for sending emails
   */
  timeoutSeconds?: number | null;

  /**
   * SMTP username (for SMTP providers)
   */
  username?: string | null;
}
