/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Request DTO for updating a single translation
 */
export interface UpdateTranslationRequest {

  /**
   * Context/notes (optional)
   */
  context?: string | null;

  /**
   * Whether this is machine-translated
   */
  isMachineTranslated?: boolean | null;

  /**
   * Source text (optional)
   */
  sourceText?: string | null;

  /**
   * New translated value
   */
  value: string;
}
