/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * DTO for updating a group's visibility
 */
export interface UpdateGroupVisibilityDto {

  /**
   * Whether the group should be publicly visible
   */
  isPublic?: boolean;
}
