/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SettingOption } from '../models/setting-option';
import { SettingUiConfig } from '../models/setting-ui-config';
import { SettingValidation } from '../models/setting-validation';

/**
 * Request to create or update a catalog entry
 */
export interface UpsertCatalogEntryRequest {
  category?: string;
  default?: any | null;
  description?: string | null;
  i18nKey?: string | null;
  immutable?: boolean;
  key?: string;
  label?: string;
  options?: Array<SettingOption> | null;
  required?: boolean;
  sensitive?: boolean;
  type?: string;

  /**
   * UI configuration for a setting
   */
  ui?: SettingUiConfig | null;

  /**
   * Validation rules for a setting
   */
  validation?: SettingValidation | null;
  version?: number;
}
