/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ThemeDto } from '../models/theme-dto';

/**
 * DTO for user theme preferences
 */
export interface UserThemeDto {

  /**
   * The dark theme details
   */
  darkTheme?: ThemeDto | null;

  /**
   * ID of the selected theme for dark mode
   */
  darkThemeId?: string;

  /**
   * The light theme details
   */
  lightTheme?: ThemeDto | null;

  /**
   * ID of the selected theme for light mode
   */
  lightThemeId?: string;

  /**
   * Whether to sync with system settings
   */
  syncWithSystem?: boolean;
}
