/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Request to validate settings without saving
 */
export interface ValidateSettingsRequest {
  category?: string;
  payload?: {
[key: string]: any;
};
}
