/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * DTO for verify security code request
 */
export interface VerifySecurityCodeDto {

  /**
   * Security code to verify
   */
  code?: string;

  /**
   * User's email address
   */
  email?: string;

  /**
   * Purpose of the security code
   */
  purpose?: string;
}
