/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Video message content - immutable value object.
 * Extends FileContent with video-specific properties.
 */
export interface VideoContent {

  /**
   * Discriminator (always 'video')
   */
  contentType: string;
}
