/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * DTO for voting on a poll option
 */
export interface VotePollDto {

  /**
   * IDs of the poll options to vote for
   */
  optionIds: Array<string>;
}
