/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ApiResponse } from '../models/api-response';
import { apiSettingsCatalogGet$Json } from '../fn/catalog/api-settings-catalog-get-json';
import { ApiSettingsCatalogGet$Json$Params } from '../fn/catalog/api-settings-catalog-get-json';
import { apiSettingsCatalogGet$Plain } from '../fn/catalog/api-settings-catalog-get-plain';
import { ApiSettingsCatalogGet$Plain$Params } from '../fn/catalog/api-settings-catalog-get-plain';
import { apiSettingsCatalogKeyDelete$Json } from '../fn/catalog/api-settings-catalog-key-delete-json';
import { ApiSettingsCatalogKeyDelete$Json$Params } from '../fn/catalog/api-settings-catalog-key-delete-json';
import { apiSettingsCatalogKeyDelete$Plain } from '../fn/catalog/api-settings-catalog-key-delete-plain';
import { ApiSettingsCatalogKeyDelete$Plain$Params } from '../fn/catalog/api-settings-catalog-key-delete-plain';
import { apiSettingsCatalogKeyGet$Json } from '../fn/catalog/api-settings-catalog-key-get-json';
import { ApiSettingsCatalogKeyGet$Json$Params } from '../fn/catalog/api-settings-catalog-key-get-json';
import { apiSettingsCatalogKeyGet$Plain } from '../fn/catalog/api-settings-catalog-key-get-plain';
import { ApiSettingsCatalogKeyGet$Plain$Params } from '../fn/catalog/api-settings-catalog-key-get-plain';
import { apiSettingsCatalogKeyPut$Json } from '../fn/catalog/api-settings-catalog-key-put-json';
import { ApiSettingsCatalogKeyPut$Json$Params } from '../fn/catalog/api-settings-catalog-key-put-json';
import { apiSettingsCatalogKeyPut$Plain } from '../fn/catalog/api-settings-catalog-key-put-plain';
import { ApiSettingsCatalogKeyPut$Plain$Params } from '../fn/catalog/api-settings-catalog-key-put-plain';
import { apiSettingsCatalogPost$Json } from '../fn/catalog/api-settings-catalog-post-json';
import { ApiSettingsCatalogPost$Json$Params } from '../fn/catalog/api-settings-catalog-post-json';
import { apiSettingsCatalogPost$Plain } from '../fn/catalog/api-settings-catalog-post-plain';
import { ApiSettingsCatalogPost$Plain$Params } from '../fn/catalog/api-settings-catalog-post-plain';
import { CatalogEntryDtoApiResponse } from '../models/catalog-entry-dto-api-response';
import { CatalogResponseApiResponse } from '../models/catalog-response-api-response';
import { ObjectApiResponse } from '../models/object-api-response';

@Injectable({ providedIn: 'root' })
export class CatalogService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiSettingsCatalogGet()` */
  static readonly ApiSettingsCatalogGetPath = '/api/settings/Catalog';

  /**
   * Gets the settings catalog organized by categories.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiSettingsCatalogGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSettingsCatalogGet$Plain$Response(params?: ApiSettingsCatalogGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<CatalogResponseApiResponse>> {
    return apiSettingsCatalogGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * Gets the settings catalog organized by categories.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiSettingsCatalogGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSettingsCatalogGet$Plain(params?: ApiSettingsCatalogGet$Plain$Params, context?: HttpContext): Observable<CatalogResponseApiResponse> {
    return this.apiSettingsCatalogGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<CatalogResponseApiResponse>): CatalogResponseApiResponse => r.body)
    );
  }

  /**
   * Gets the settings catalog organized by categories.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiSettingsCatalogGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSettingsCatalogGet$Json$Response(params?: ApiSettingsCatalogGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<CatalogResponseApiResponse>> {
    return apiSettingsCatalogGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * Gets the settings catalog organized by categories.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiSettingsCatalogGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSettingsCatalogGet$Json(params?: ApiSettingsCatalogGet$Json$Params, context?: HttpContext): Observable<CatalogResponseApiResponse> {
    return this.apiSettingsCatalogGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<CatalogResponseApiResponse>): CatalogResponseApiResponse => r.body)
    );
  }

  /** Path part for operation `apiSettingsCatalogPost()` */
  static readonly ApiSettingsCatalogPostPath = '/api/settings/Catalog';

  /**
   * Creates or updates a catalog entry (admin only).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiSettingsCatalogPost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiSettingsCatalogPost$Plain$Response(params?: ApiSettingsCatalogPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<CatalogEntryDtoApiResponse>> {
    return apiSettingsCatalogPost$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * Creates or updates a catalog entry (admin only).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiSettingsCatalogPost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiSettingsCatalogPost$Plain(params?: ApiSettingsCatalogPost$Plain$Params, context?: HttpContext): Observable<CatalogEntryDtoApiResponse> {
    return this.apiSettingsCatalogPost$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<CatalogEntryDtoApiResponse>): CatalogEntryDtoApiResponse => r.body)
    );
  }

  /**
   * Creates or updates a catalog entry (admin only).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiSettingsCatalogPost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiSettingsCatalogPost$Json$Response(params?: ApiSettingsCatalogPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<CatalogEntryDtoApiResponse>> {
    return apiSettingsCatalogPost$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * Creates or updates a catalog entry (admin only).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiSettingsCatalogPost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiSettingsCatalogPost$Json(params?: ApiSettingsCatalogPost$Json$Params, context?: HttpContext): Observable<CatalogEntryDtoApiResponse> {
    return this.apiSettingsCatalogPost$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<CatalogEntryDtoApiResponse>): CatalogEntryDtoApiResponse => r.body)
    );
  }

  /** Path part for operation `apiSettingsCatalogKeyGet()` */
  static readonly ApiSettingsCatalogKeyGetPath = '/api/settings/Catalog/{key}';

  /**
   * Gets a single catalog entry by key.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiSettingsCatalogKeyGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSettingsCatalogKeyGet$Plain$Response(params: ApiSettingsCatalogKeyGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<CatalogEntryDtoApiResponse>> {
    return apiSettingsCatalogKeyGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * Gets a single catalog entry by key.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiSettingsCatalogKeyGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSettingsCatalogKeyGet$Plain(params: ApiSettingsCatalogKeyGet$Plain$Params, context?: HttpContext): Observable<CatalogEntryDtoApiResponse> {
    return this.apiSettingsCatalogKeyGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<CatalogEntryDtoApiResponse>): CatalogEntryDtoApiResponse => r.body)
    );
  }

  /**
   * Gets a single catalog entry by key.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiSettingsCatalogKeyGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSettingsCatalogKeyGet$Json$Response(params: ApiSettingsCatalogKeyGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<CatalogEntryDtoApiResponse>> {
    return apiSettingsCatalogKeyGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * Gets a single catalog entry by key.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiSettingsCatalogKeyGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSettingsCatalogKeyGet$Json(params: ApiSettingsCatalogKeyGet$Json$Params, context?: HttpContext): Observable<CatalogEntryDtoApiResponse> {
    return this.apiSettingsCatalogKeyGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<CatalogEntryDtoApiResponse>): CatalogEntryDtoApiResponse => r.body)
    );
  }

  /** Path part for operation `apiSettingsCatalogKeyPut()` */
  static readonly ApiSettingsCatalogKeyPutPath = '/api/settings/Catalog/{key}';

  /**
   * Updates a catalog entry (admin only).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiSettingsCatalogKeyPut$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiSettingsCatalogKeyPut$Plain$Response(params: ApiSettingsCatalogKeyPut$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<CatalogEntryDtoApiResponse>> {
    return apiSettingsCatalogKeyPut$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * Updates a catalog entry (admin only).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiSettingsCatalogKeyPut$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiSettingsCatalogKeyPut$Plain(params: ApiSettingsCatalogKeyPut$Plain$Params, context?: HttpContext): Observable<CatalogEntryDtoApiResponse> {
    return this.apiSettingsCatalogKeyPut$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<CatalogEntryDtoApiResponse>): CatalogEntryDtoApiResponse => r.body)
    );
  }

  /**
   * Updates a catalog entry (admin only).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiSettingsCatalogKeyPut$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiSettingsCatalogKeyPut$Json$Response(params: ApiSettingsCatalogKeyPut$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<CatalogEntryDtoApiResponse>> {
    return apiSettingsCatalogKeyPut$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * Updates a catalog entry (admin only).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiSettingsCatalogKeyPut$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiSettingsCatalogKeyPut$Json(params: ApiSettingsCatalogKeyPut$Json$Params, context?: HttpContext): Observable<CatalogEntryDtoApiResponse> {
    return this.apiSettingsCatalogKeyPut$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<CatalogEntryDtoApiResponse>): CatalogEntryDtoApiResponse => r.body)
    );
  }

  /** Path part for operation `apiSettingsCatalogKeyDelete()` */
  static readonly ApiSettingsCatalogKeyDeletePath = '/api/settings/Catalog/{key}';

  /**
   * Deletes (deprecates) a catalog entry (admin only).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiSettingsCatalogKeyDelete$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSettingsCatalogKeyDelete$Plain$Response(params: ApiSettingsCatalogKeyDelete$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<(ObjectApiResponse | ApiResponse)>> {
    return apiSettingsCatalogKeyDelete$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * Deletes (deprecates) a catalog entry (admin only).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiSettingsCatalogKeyDelete$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSettingsCatalogKeyDelete$Plain(params: ApiSettingsCatalogKeyDelete$Plain$Params, context?: HttpContext): Observable<(ObjectApiResponse | ApiResponse)> {
    return this.apiSettingsCatalogKeyDelete$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<(ObjectApiResponse | ApiResponse)>): (ObjectApiResponse | ApiResponse) => r.body)
    );
  }

  /**
   * Deletes (deprecates) a catalog entry (admin only).
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiSettingsCatalogKeyDelete$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSettingsCatalogKeyDelete$Json$Response(params: ApiSettingsCatalogKeyDelete$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<(ObjectApiResponse | ApiResponse)>> {
    return apiSettingsCatalogKeyDelete$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * Deletes (deprecates) a catalog entry (admin only).
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiSettingsCatalogKeyDelete$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiSettingsCatalogKeyDelete$Json(params: ApiSettingsCatalogKeyDelete$Json$Params, context?: HttpContext): Observable<(ObjectApiResponse | ApiResponse)> {
    return this.apiSettingsCatalogKeyDelete$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<(ObjectApiResponse | ApiResponse)>): (ObjectApiResponse | ApiResponse) => r.body)
    );
  }

}
