/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiAdminEmailProvidersGet$Json } from '../fn/email-provider-admin/api-admin-email-providers-get-json';
import { ApiAdminEmailProvidersGet$Json$Params } from '../fn/email-provider-admin/api-admin-email-providers-get-json';
import { apiAdminEmailProvidersGet$Plain } from '../fn/email-provider-admin/api-admin-email-providers-get-plain';
import { ApiAdminEmailProvidersGet$Plain$Params } from '../fn/email-provider-admin/api-admin-email-providers-get-plain';
import { apiAdminEmailProvidersIdDelete$Json } from '../fn/email-provider-admin/api-admin-email-providers-id-delete-json';
import { ApiAdminEmailProvidersIdDelete$Json$Params } from '../fn/email-provider-admin/api-admin-email-providers-id-delete-json';
import { apiAdminEmailProvidersIdDelete$Plain } from '../fn/email-provider-admin/api-admin-email-providers-id-delete-plain';
import { ApiAdminEmailProvidersIdDelete$Plain$Params } from '../fn/email-provider-admin/api-admin-email-providers-id-delete-plain';
import { apiAdminEmailProvidersIdGet$Json } from '../fn/email-provider-admin/api-admin-email-providers-id-get-json';
import { ApiAdminEmailProvidersIdGet$Json$Params } from '../fn/email-provider-admin/api-admin-email-providers-id-get-json';
import { apiAdminEmailProvidersIdGet$Plain } from '../fn/email-provider-admin/api-admin-email-providers-id-get-plain';
import { ApiAdminEmailProvidersIdGet$Plain$Params } from '../fn/email-provider-admin/api-admin-email-providers-id-get-plain';
import { apiAdminEmailProvidersIdPut$Json } from '../fn/email-provider-admin/api-admin-email-providers-id-put-json';
import { ApiAdminEmailProvidersIdPut$Json$Params } from '../fn/email-provider-admin/api-admin-email-providers-id-put-json';
import { apiAdminEmailProvidersIdPut$Plain } from '../fn/email-provider-admin/api-admin-email-providers-id-put-plain';
import { ApiAdminEmailProvidersIdPut$Plain$Params } from '../fn/email-provider-admin/api-admin-email-providers-id-put-plain';
import { apiAdminEmailProvidersIdSetDefaultPost$Json } from '../fn/email-provider-admin/api-admin-email-providers-id-set-default-post-json';
import { ApiAdminEmailProvidersIdSetDefaultPost$Json$Params } from '../fn/email-provider-admin/api-admin-email-providers-id-set-default-post-json';
import { apiAdminEmailProvidersIdSetDefaultPost$Plain } from '../fn/email-provider-admin/api-admin-email-providers-id-set-default-post-plain';
import { ApiAdminEmailProvidersIdSetDefaultPost$Plain$Params } from '../fn/email-provider-admin/api-admin-email-providers-id-set-default-post-plain';
import { apiAdminEmailProvidersPost$Json } from '../fn/email-provider-admin/api-admin-email-providers-post-json';
import { ApiAdminEmailProvidersPost$Json$Params } from '../fn/email-provider-admin/api-admin-email-providers-post-json';
import { apiAdminEmailProvidersPost$Plain } from '../fn/email-provider-admin/api-admin-email-providers-post-plain';
import { ApiAdminEmailProvidersPost$Plain$Params } from '../fn/email-provider-admin/api-admin-email-providers-post-plain';
import { ApiResponse } from '../models/api-response';
import { EmailProviderDtoApiResponse } from '../models/email-provider-dto-api-response';
import { EmailProviderDtoIEnumerableApiResponse } from '../models/email-provider-dto-i-enumerable-api-response';
import { ObjectApiResponse } from '../models/object-api-response';

@Injectable({ providedIn: 'root' })
export class EmailProviderAdminService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiAdminEmailProvidersGet()` */
  static readonly ApiAdminEmailProvidersGetPath = '/api/admin/email-providers';

  /**
   * Gets all email providers.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAdminEmailProvidersGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAdminEmailProvidersGet$Plain$Response(params?: ApiAdminEmailProvidersGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<EmailProviderDtoIEnumerableApiResponse>> {
    return apiAdminEmailProvidersGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * Gets all email providers.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAdminEmailProvidersGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAdminEmailProvidersGet$Plain(params?: ApiAdminEmailProvidersGet$Plain$Params, context?: HttpContext): Observable<EmailProviderDtoIEnumerableApiResponse> {
    return this.apiAdminEmailProvidersGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<EmailProviderDtoIEnumerableApiResponse>): EmailProviderDtoIEnumerableApiResponse => r.body)
    );
  }

  /**
   * Gets all email providers.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAdminEmailProvidersGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAdminEmailProvidersGet$Json$Response(params?: ApiAdminEmailProvidersGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<EmailProviderDtoIEnumerableApiResponse>> {
    return apiAdminEmailProvidersGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * Gets all email providers.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAdminEmailProvidersGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAdminEmailProvidersGet$Json(params?: ApiAdminEmailProvidersGet$Json$Params, context?: HttpContext): Observable<EmailProviderDtoIEnumerableApiResponse> {
    return this.apiAdminEmailProvidersGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<EmailProviderDtoIEnumerableApiResponse>): EmailProviderDtoIEnumerableApiResponse => r.body)
    );
  }

  /** Path part for operation `apiAdminEmailProvidersPost()` */
  static readonly ApiAdminEmailProvidersPostPath = '/api/admin/email-providers';

  /**
   * Creates a new email provider.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAdminEmailProvidersPost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAdminEmailProvidersPost$Plain$Response(params?: ApiAdminEmailProvidersPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<EmailProviderDtoApiResponse>> {
    return apiAdminEmailProvidersPost$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * Creates a new email provider.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAdminEmailProvidersPost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAdminEmailProvidersPost$Plain(params?: ApiAdminEmailProvidersPost$Plain$Params, context?: HttpContext): Observable<EmailProviderDtoApiResponse> {
    return this.apiAdminEmailProvidersPost$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<EmailProviderDtoApiResponse>): EmailProviderDtoApiResponse => r.body)
    );
  }

  /**
   * Creates a new email provider.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAdminEmailProvidersPost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAdminEmailProvidersPost$Json$Response(params?: ApiAdminEmailProvidersPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<EmailProviderDtoApiResponse>> {
    return apiAdminEmailProvidersPost$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * Creates a new email provider.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAdminEmailProvidersPost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAdminEmailProvidersPost$Json(params?: ApiAdminEmailProvidersPost$Json$Params, context?: HttpContext): Observable<EmailProviderDtoApiResponse> {
    return this.apiAdminEmailProvidersPost$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<EmailProviderDtoApiResponse>): EmailProviderDtoApiResponse => r.body)
    );
  }

  /** Path part for operation `apiAdminEmailProvidersIdGet()` */
  static readonly ApiAdminEmailProvidersIdGetPath = '/api/admin/email-providers/{id}';

  /**
   * Gets a specific email provider by ID.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAdminEmailProvidersIdGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAdminEmailProvidersIdGet$Plain$Response(params: ApiAdminEmailProvidersIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<EmailProviderDtoApiResponse>> {
    return apiAdminEmailProvidersIdGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * Gets a specific email provider by ID.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAdminEmailProvidersIdGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAdminEmailProvidersIdGet$Plain(params: ApiAdminEmailProvidersIdGet$Plain$Params, context?: HttpContext): Observable<EmailProviderDtoApiResponse> {
    return this.apiAdminEmailProvidersIdGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<EmailProviderDtoApiResponse>): EmailProviderDtoApiResponse => r.body)
    );
  }

  /**
   * Gets a specific email provider by ID.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAdminEmailProvidersIdGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAdminEmailProvidersIdGet$Json$Response(params: ApiAdminEmailProvidersIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<EmailProviderDtoApiResponse>> {
    return apiAdminEmailProvidersIdGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * Gets a specific email provider by ID.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAdminEmailProvidersIdGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAdminEmailProvidersIdGet$Json(params: ApiAdminEmailProvidersIdGet$Json$Params, context?: HttpContext): Observable<EmailProviderDtoApiResponse> {
    return this.apiAdminEmailProvidersIdGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<EmailProviderDtoApiResponse>): EmailProviderDtoApiResponse => r.body)
    );
  }

  /** Path part for operation `apiAdminEmailProvidersIdPut()` */
  static readonly ApiAdminEmailProvidersIdPutPath = '/api/admin/email-providers/{id}';

  /**
   * Updates an existing email provider.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAdminEmailProvidersIdPut$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAdminEmailProvidersIdPut$Plain$Response(params: ApiAdminEmailProvidersIdPut$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<EmailProviderDtoApiResponse>> {
    return apiAdminEmailProvidersIdPut$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * Updates an existing email provider.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAdminEmailProvidersIdPut$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAdminEmailProvidersIdPut$Plain(params: ApiAdminEmailProvidersIdPut$Plain$Params, context?: HttpContext): Observable<EmailProviderDtoApiResponse> {
    return this.apiAdminEmailProvidersIdPut$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<EmailProviderDtoApiResponse>): EmailProviderDtoApiResponse => r.body)
    );
  }

  /**
   * Updates an existing email provider.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAdminEmailProvidersIdPut$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAdminEmailProvidersIdPut$Json$Response(params: ApiAdminEmailProvidersIdPut$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<EmailProviderDtoApiResponse>> {
    return apiAdminEmailProvidersIdPut$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * Updates an existing email provider.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAdminEmailProvidersIdPut$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAdminEmailProvidersIdPut$Json(params: ApiAdminEmailProvidersIdPut$Json$Params, context?: HttpContext): Observable<EmailProviderDtoApiResponse> {
    return this.apiAdminEmailProvidersIdPut$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<EmailProviderDtoApiResponse>): EmailProviderDtoApiResponse => r.body)
    );
  }

  /** Path part for operation `apiAdminEmailProvidersIdDelete()` */
  static readonly ApiAdminEmailProvidersIdDeletePath = '/api/admin/email-providers/{id}';

  /**
   * Deletes an email provider.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAdminEmailProvidersIdDelete$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAdminEmailProvidersIdDelete$Plain$Response(params: ApiAdminEmailProvidersIdDelete$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<(ObjectApiResponse | ApiResponse)>> {
    return apiAdminEmailProvidersIdDelete$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * Deletes an email provider.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAdminEmailProvidersIdDelete$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAdminEmailProvidersIdDelete$Plain(params: ApiAdminEmailProvidersIdDelete$Plain$Params, context?: HttpContext): Observable<(ObjectApiResponse | ApiResponse)> {
    return this.apiAdminEmailProvidersIdDelete$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<(ObjectApiResponse | ApiResponse)>): (ObjectApiResponse | ApiResponse) => r.body)
    );
  }

  /**
   * Deletes an email provider.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAdminEmailProvidersIdDelete$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAdminEmailProvidersIdDelete$Json$Response(params: ApiAdminEmailProvidersIdDelete$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<(ObjectApiResponse | ApiResponse)>> {
    return apiAdminEmailProvidersIdDelete$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * Deletes an email provider.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAdminEmailProvidersIdDelete$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAdminEmailProvidersIdDelete$Json(params: ApiAdminEmailProvidersIdDelete$Json$Params, context?: HttpContext): Observable<(ObjectApiResponse | ApiResponse)> {
    return this.apiAdminEmailProvidersIdDelete$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<(ObjectApiResponse | ApiResponse)>): (ObjectApiResponse | ApiResponse) => r.body)
    );
  }

  /** Path part for operation `apiAdminEmailProvidersIdSetDefaultPost()` */
  static readonly ApiAdminEmailProvidersIdSetDefaultPostPath = '/api/admin/email-providers/{id}/set-default';

  /**
   * Sets a provider as the default.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAdminEmailProvidersIdSetDefaultPost$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAdminEmailProvidersIdSetDefaultPost$Plain$Response(params: ApiAdminEmailProvidersIdSetDefaultPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<(ObjectApiResponse | ApiResponse)>> {
    return apiAdminEmailProvidersIdSetDefaultPost$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * Sets a provider as the default.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAdminEmailProvidersIdSetDefaultPost$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAdminEmailProvidersIdSetDefaultPost$Plain(params: ApiAdminEmailProvidersIdSetDefaultPost$Plain$Params, context?: HttpContext): Observable<(ObjectApiResponse | ApiResponse)> {
    return this.apiAdminEmailProvidersIdSetDefaultPost$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<(ObjectApiResponse | ApiResponse)>): (ObjectApiResponse | ApiResponse) => r.body)
    );
  }

  /**
   * Sets a provider as the default.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAdminEmailProvidersIdSetDefaultPost$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAdminEmailProvidersIdSetDefaultPost$Json$Response(params: ApiAdminEmailProvidersIdSetDefaultPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<(ObjectApiResponse | ApiResponse)>> {
    return apiAdminEmailProvidersIdSetDefaultPost$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * Sets a provider as the default.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAdminEmailProvidersIdSetDefaultPost$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAdminEmailProvidersIdSetDefaultPost$Json(params: ApiAdminEmailProvidersIdSetDefaultPost$Json$Params, context?: HttpContext): Observable<(ObjectApiResponse | ApiResponse)> {
    return this.apiAdminEmailProvidersIdSetDefaultPost$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<(ObjectApiResponse | ApiResponse)>): (ObjectApiResponse | ApiResponse) => r.body)
    );
  }

}
