/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiHealthAliveGet } from '../fn/health/api-health-alive-get';
import { ApiHealthAliveGet$Params } from '../fn/health/api-health-alive-get';
import { apiHealthGet } from '../fn/health/api-health-get';
import { ApiHealthGet$Params } from '../fn/health/api-health-get';
import { apiHealthReadyGet } from '../fn/health/api-health-ready-get';
import { ApiHealthReadyGet$Params } from '../fn/health/api-health-ready-get';
import { ApiResponse } from '../models/api-response';
import { ObjectApiResponse } from '../models/object-api-response';

@Injectable({ providedIn: 'root' })
export class HealthService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiHealthGet()` */
  static readonly ApiHealthGetPath = '/api/health';

  /**
   * Basic health check endpoint.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiHealthGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiHealthGet$Response(params?: ApiHealthGet$Params, context?: HttpContext): Observable<StrictHttpResponse<(ObjectApiResponse | ApiResponse)>> {
    return apiHealthGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Basic health check endpoint.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiHealthGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiHealthGet(params?: ApiHealthGet$Params, context?: HttpContext): Observable<(ObjectApiResponse | ApiResponse)> {
    return this.apiHealthGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<(ObjectApiResponse | ApiResponse)>): (ObjectApiResponse | ApiResponse) => r.body)
    );
  }

  /** Path part for operation `apiHealthReadyGet()` */
  static readonly ApiHealthReadyGetPath = '/api/health/ready';

  /**
   * Readiness probe for Kubernetes/container orchestration.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiHealthReadyGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiHealthReadyGet$Response(params?: ApiHealthReadyGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiHealthReadyGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Readiness probe for Kubernetes/container orchestration.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiHealthReadyGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiHealthReadyGet(params?: ApiHealthReadyGet$Params, context?: HttpContext): Observable<void> {
    return this.apiHealthReadyGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiHealthAliveGet()` */
  static readonly ApiHealthAliveGetPath = '/api/health/alive';

  /**
   * Liveness probe for Kubernetes/container orchestration.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiHealthAliveGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiHealthAliveGet$Response(params?: ApiHealthAliveGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiHealthAliveGet(this.http, this.rootUrl, params, context);
  }

  /**
   * Liveness probe for Kubernetes/container orchestration.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiHealthAliveGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiHealthAliveGet(params?: ApiHealthAliveGet$Params, context?: HttpContext): Observable<void> {
    return this.apiHealthAliveGet$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
