/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiI18NLangCategoryCategoryKeyGet$Json } from '../fn/i-18-n/api-i-18-n-lang-category-category-key-get-json';
import { ApiI18NLangCategoryCategoryKeyGet$Json$Params } from '../fn/i-18-n/api-i-18-n-lang-category-category-key-get-json';
import { apiI18NLangCategoryCategoryKeyGet$Plain } from '../fn/i-18-n/api-i-18-n-lang-category-category-key-get-plain';
import { ApiI18NLangCategoryCategoryKeyGet$Plain$Params } from '../fn/i-18-n/api-i-18-n-lang-category-category-key-get-plain';
import { apiI18NLangGet$Json } from '../fn/i-18-n/api-i-18-n-lang-get-json';
import { ApiI18NLangGet$Json$Params } from '../fn/i-18-n/api-i-18-n-lang-get-json';
import { apiI18NLangGet$Plain } from '../fn/i-18-n/api-i-18-n-lang-get-plain';
import { ApiI18NLangGet$Plain$Params } from '../fn/i-18-n/api-i-18-n-lang-get-plain';
import { apiI18NLangKeysGet$Json } from '../fn/i-18-n/api-i-18-n-lang-keys-get-json';
import { ApiI18NLangKeysGet$Json$Params } from '../fn/i-18-n/api-i-18-n-lang-keys-get-json';
import { apiI18NLangKeysGet$Plain } from '../fn/i-18-n/api-i-18-n-lang-keys-get-plain';
import { ApiI18NLangKeysGet$Plain$Params } from '../fn/i-18-n/api-i-18-n-lang-keys-get-plain';
import { apiI18NLangSearchGet$Json } from '../fn/i-18-n/api-i-18-n-lang-search-get-json';
import { ApiI18NLangSearchGet$Json$Params } from '../fn/i-18-n/api-i-18-n-lang-search-get-json';
import { apiI18NLangSearchGet$Plain } from '../fn/i-18-n/api-i-18-n-lang-search-get-plain';
import { ApiI18NLangSearchGet$Plain$Params } from '../fn/i-18-n/api-i-18-n-lang-search-get-plain';
import { apiI18NMetadataGet$Json } from '../fn/i-18-n/api-i-18-n-metadata-get-json';
import { ApiI18NMetadataGet$Json$Params } from '../fn/i-18-n/api-i-18-n-metadata-get-json';
import { apiI18NMetadataGet$Plain } from '../fn/i-18-n/api-i-18-n-metadata-get-plain';
import { ApiI18NMetadataGet$Plain$Params } from '../fn/i-18-n/api-i-18-n-metadata-get-plain';
import { I18NMetadataDtoApiResponse } from '../models/i-18-n-metadata-dto-api-response';
import { TranslationPayloadDtoApiResponse } from '../models/translation-payload-dto-api-response';
import { TranslationSearchResultDtoApiResponse } from '../models/translation-search-result-dto-api-response';

@Injectable({ providedIn: 'root' })
export class I18NService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiI18NLangGet()` */
  static readonly ApiI18NLangGetPath = '/api/i18n/{lang}';

  /**
   * Gets all translations for a specific language.
   * Returns nested JSON by default for easy use with i18n libraries.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiI18NLangGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiI18NLangGet$Plain$Response(params: ApiI18NLangGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<TranslationPayloadDtoApiResponse>> {
    return apiI18NLangGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * Gets all translations for a specific language.
   * Returns nested JSON by default for easy use with i18n libraries.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiI18NLangGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiI18NLangGet$Plain(params: ApiI18NLangGet$Plain$Params, context?: HttpContext): Observable<TranslationPayloadDtoApiResponse> {
    return this.apiI18NLangGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<TranslationPayloadDtoApiResponse>): TranslationPayloadDtoApiResponse => r.body)
    );
  }

  /**
   * Gets all translations for a specific language.
   * Returns nested JSON by default for easy use with i18n libraries.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiI18NLangGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiI18NLangGet$Json$Response(params: ApiI18NLangGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<TranslationPayloadDtoApiResponse>> {
    return apiI18NLangGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * Gets all translations for a specific language.
   * Returns nested JSON by default for easy use with i18n libraries.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiI18NLangGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiI18NLangGet$Json(params: ApiI18NLangGet$Json$Params, context?: HttpContext): Observable<TranslationPayloadDtoApiResponse> {
    return this.apiI18NLangGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<TranslationPayloadDtoApiResponse>): TranslationPayloadDtoApiResponse => r.body)
    );
  }

  /** Path part for operation `apiI18NLangCategoryCategoryKeyGet()` */
  static readonly ApiI18NLangCategoryCategoryKeyGetPath = '/api/i18n/{lang}/category/{categoryKey}';

  /**
   * Gets translations for a specific category within a language.
   * Useful for lazy-loading translations for specific sections.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiI18NLangCategoryCategoryKeyGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiI18NLangCategoryCategoryKeyGet$Plain$Response(params: ApiI18NLangCategoryCategoryKeyGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<TranslationPayloadDtoApiResponse>> {
    return apiI18NLangCategoryCategoryKeyGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * Gets translations for a specific category within a language.
   * Useful for lazy-loading translations for specific sections.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiI18NLangCategoryCategoryKeyGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiI18NLangCategoryCategoryKeyGet$Plain(params: ApiI18NLangCategoryCategoryKeyGet$Plain$Params, context?: HttpContext): Observable<TranslationPayloadDtoApiResponse> {
    return this.apiI18NLangCategoryCategoryKeyGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<TranslationPayloadDtoApiResponse>): TranslationPayloadDtoApiResponse => r.body)
    );
  }

  /**
   * Gets translations for a specific category within a language.
   * Useful for lazy-loading translations for specific sections.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiI18NLangCategoryCategoryKeyGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiI18NLangCategoryCategoryKeyGet$Json$Response(params: ApiI18NLangCategoryCategoryKeyGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<TranslationPayloadDtoApiResponse>> {
    return apiI18NLangCategoryCategoryKeyGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * Gets translations for a specific category within a language.
   * Useful for lazy-loading translations for specific sections.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiI18NLangCategoryCategoryKeyGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiI18NLangCategoryCategoryKeyGet$Json(params: ApiI18NLangCategoryCategoryKeyGet$Json$Params, context?: HttpContext): Observable<TranslationPayloadDtoApiResponse> {
    return this.apiI18NLangCategoryCategoryKeyGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<TranslationPayloadDtoApiResponse>): TranslationPayloadDtoApiResponse => r.body)
    );
  }

  /** Path part for operation `apiI18NLangKeysGet()` */
  static readonly ApiI18NLangKeysGetPath = '/api/i18n/{lang}/keys';

  /**
   * Gets translations for specific keys.
   * Useful for fetching only required translations.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiI18NLangKeysGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiI18NLangKeysGet$Plain$Response(params: ApiI18NLangKeysGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<TranslationPayloadDtoApiResponse>> {
    return apiI18NLangKeysGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * Gets translations for specific keys.
   * Useful for fetching only required translations.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiI18NLangKeysGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiI18NLangKeysGet$Plain(params: ApiI18NLangKeysGet$Plain$Params, context?: HttpContext): Observable<TranslationPayloadDtoApiResponse> {
    return this.apiI18NLangKeysGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<TranslationPayloadDtoApiResponse>): TranslationPayloadDtoApiResponse => r.body)
    );
  }

  /**
   * Gets translations for specific keys.
   * Useful for fetching only required translations.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiI18NLangKeysGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiI18NLangKeysGet$Json$Response(params: ApiI18NLangKeysGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<TranslationPayloadDtoApiResponse>> {
    return apiI18NLangKeysGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * Gets translations for specific keys.
   * Useful for fetching only required translations.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiI18NLangKeysGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiI18NLangKeysGet$Json(params: ApiI18NLangKeysGet$Json$Params, context?: HttpContext): Observable<TranslationPayloadDtoApiResponse> {
    return this.apiI18NLangKeysGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<TranslationPayloadDtoApiResponse>): TranslationPayloadDtoApiResponse => r.body)
    );
  }

  /** Path part for operation `apiI18NLangSearchGet()` */
  static readonly ApiI18NLangSearchGetPath = '/api/i18n/{lang}/search';

  /**
   * Searches translations by value or key.
   * Supports pagination for large result sets.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiI18NLangSearchGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiI18NLangSearchGet$Plain$Response(params: ApiI18NLangSearchGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<TranslationSearchResultDtoApiResponse>> {
    return apiI18NLangSearchGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * Searches translations by value or key.
   * Supports pagination for large result sets.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiI18NLangSearchGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiI18NLangSearchGet$Plain(params: ApiI18NLangSearchGet$Plain$Params, context?: HttpContext): Observable<TranslationSearchResultDtoApiResponse> {
    return this.apiI18NLangSearchGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<TranslationSearchResultDtoApiResponse>): TranslationSearchResultDtoApiResponse => r.body)
    );
  }

  /**
   * Searches translations by value or key.
   * Supports pagination for large result sets.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiI18NLangSearchGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiI18NLangSearchGet$Json$Response(params: ApiI18NLangSearchGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<TranslationSearchResultDtoApiResponse>> {
    return apiI18NLangSearchGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * Searches translations by value or key.
   * Supports pagination for large result sets.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiI18NLangSearchGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiI18NLangSearchGet$Json(params: ApiI18NLangSearchGet$Json$Params, context?: HttpContext): Observable<TranslationSearchResultDtoApiResponse> {
    return this.apiI18NLangSearchGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<TranslationSearchResultDtoApiResponse>): TranslationSearchResultDtoApiResponse => r.body)
    );
  }

  /** Path part for operation `apiI18NMetadataGet()` */
  static readonly ApiI18NMetadataGetPath = '/api/i18n/metadata';

  /**
   * Gets i18n metadata including supported languages and categories.
   * Use this endpoint to discover available languages and build language selectors.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiI18NMetadataGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiI18NMetadataGet$Plain$Response(params?: ApiI18NMetadataGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<I18NMetadataDtoApiResponse>> {
    return apiI18NMetadataGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * Gets i18n metadata including supported languages and categories.
   * Use this endpoint to discover available languages and build language selectors.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiI18NMetadataGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiI18NMetadataGet$Plain(params?: ApiI18NMetadataGet$Plain$Params, context?: HttpContext): Observable<I18NMetadataDtoApiResponse> {
    return this.apiI18NMetadataGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<I18NMetadataDtoApiResponse>): I18NMetadataDtoApiResponse => r.body)
    );
  }

  /**
   * Gets i18n metadata including supported languages and categories.
   * Use this endpoint to discover available languages and build language selectors.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiI18NMetadataGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiI18NMetadataGet$Json$Response(params?: ApiI18NMetadataGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<I18NMetadataDtoApiResponse>> {
    return apiI18NMetadataGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * Gets i18n metadata including supported languages and categories.
   * Use this endpoint to discover available languages and build language selectors.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiI18NMetadataGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiI18NMetadataGet$Json(params?: ApiI18NMetadataGet$Json$Params, context?: HttpContext): Observable<I18NMetadataDtoApiResponse> {
    return this.apiI18NMetadataGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<I18NMetadataDtoApiResponse>): I18NMetadataDtoApiResponse => r.body)
    );
  }

}
