/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiGroupsGroupIdMessagesMessageIdPollsResultsGet$Json } from '../fn/polls/api-groups-group-id-messages-message-id-polls-results-get-json';
import { ApiGroupsGroupIdMessagesMessageIdPollsResultsGet$Json$Params } from '../fn/polls/api-groups-group-id-messages-message-id-polls-results-get-json';
import { apiGroupsGroupIdMessagesMessageIdPollsResultsGet$Plain } from '../fn/polls/api-groups-group-id-messages-message-id-polls-results-get-plain';
import { ApiGroupsGroupIdMessagesMessageIdPollsResultsGet$Plain$Params } from '../fn/polls/api-groups-group-id-messages-message-id-polls-results-get-plain';
import { apiGroupsGroupIdMessagesMessageIdPollsVoteDelete$Json } from '../fn/polls/api-groups-group-id-messages-message-id-polls-vote-delete-json';
import { ApiGroupsGroupIdMessagesMessageIdPollsVoteDelete$Json$Params } from '../fn/polls/api-groups-group-id-messages-message-id-polls-vote-delete-json';
import { apiGroupsGroupIdMessagesMessageIdPollsVoteDelete$Plain } from '../fn/polls/api-groups-group-id-messages-message-id-polls-vote-delete-plain';
import { ApiGroupsGroupIdMessagesMessageIdPollsVoteDelete$Plain$Params } from '../fn/polls/api-groups-group-id-messages-message-id-polls-vote-delete-plain';
import { apiGroupsGroupIdMessagesMessageIdPollsVotePost$Json } from '../fn/polls/api-groups-group-id-messages-message-id-polls-vote-post-json';
import { ApiGroupsGroupIdMessagesMessageIdPollsVotePost$Json$Params } from '../fn/polls/api-groups-group-id-messages-message-id-polls-vote-post-json';
import { apiGroupsGroupIdMessagesMessageIdPollsVotePost$Plain } from '../fn/polls/api-groups-group-id-messages-message-id-polls-vote-post-plain';
import { ApiGroupsGroupIdMessagesMessageIdPollsVotePost$Plain$Params } from '../fn/polls/api-groups-group-id-messages-message-id-polls-vote-post-plain';
import { PollResultsDtoApiResponse } from '../models/poll-results-dto-api-response';

@Injectable({ providedIn: 'root' })
export class PollsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiGroupsGroupIdMessagesMessageIdPollsResultsGet()` */
  static readonly ApiGroupsGroupIdMessagesMessageIdPollsResultsGetPath = '/api/groups/{groupId}/messages/{messageId}/polls/results';

  /**
   * Gets the current results for a poll.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiGroupsGroupIdMessagesMessageIdPollsResultsGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiGroupsGroupIdMessagesMessageIdPollsResultsGet$Plain$Response(params: ApiGroupsGroupIdMessagesMessageIdPollsResultsGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<PollResultsDtoApiResponse>> {
    return apiGroupsGroupIdMessagesMessageIdPollsResultsGet$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * Gets the current results for a poll.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiGroupsGroupIdMessagesMessageIdPollsResultsGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiGroupsGroupIdMessagesMessageIdPollsResultsGet$Plain(params: ApiGroupsGroupIdMessagesMessageIdPollsResultsGet$Plain$Params, context?: HttpContext): Observable<PollResultsDtoApiResponse> {
    return this.apiGroupsGroupIdMessagesMessageIdPollsResultsGet$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<PollResultsDtoApiResponse>): PollResultsDtoApiResponse => r.body)
    );
  }

  /**
   * Gets the current results for a poll.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiGroupsGroupIdMessagesMessageIdPollsResultsGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiGroupsGroupIdMessagesMessageIdPollsResultsGet$Json$Response(params: ApiGroupsGroupIdMessagesMessageIdPollsResultsGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<PollResultsDtoApiResponse>> {
    return apiGroupsGroupIdMessagesMessageIdPollsResultsGet$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * Gets the current results for a poll.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiGroupsGroupIdMessagesMessageIdPollsResultsGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiGroupsGroupIdMessagesMessageIdPollsResultsGet$Json(params: ApiGroupsGroupIdMessagesMessageIdPollsResultsGet$Json$Params, context?: HttpContext): Observable<PollResultsDtoApiResponse> {
    return this.apiGroupsGroupIdMessagesMessageIdPollsResultsGet$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<PollResultsDtoApiResponse>): PollResultsDtoApiResponse => r.body)
    );
  }

  /** Path part for operation `apiGroupsGroupIdMessagesMessageIdPollsVotePost()` */
  static readonly ApiGroupsGroupIdMessagesMessageIdPollsVotePostPath = '/api/groups/{groupId}/messages/{messageId}/polls/vote';

  /**
   * Votes on a poll option.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiGroupsGroupIdMessagesMessageIdPollsVotePost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiGroupsGroupIdMessagesMessageIdPollsVotePost$Plain$Response(params: ApiGroupsGroupIdMessagesMessageIdPollsVotePost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<PollResultsDtoApiResponse>> {
    return apiGroupsGroupIdMessagesMessageIdPollsVotePost$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * Votes on a poll option.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiGroupsGroupIdMessagesMessageIdPollsVotePost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiGroupsGroupIdMessagesMessageIdPollsVotePost$Plain(params: ApiGroupsGroupIdMessagesMessageIdPollsVotePost$Plain$Params, context?: HttpContext): Observable<PollResultsDtoApiResponse> {
    return this.apiGroupsGroupIdMessagesMessageIdPollsVotePost$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<PollResultsDtoApiResponse>): PollResultsDtoApiResponse => r.body)
    );
  }

  /**
   * Votes on a poll option.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiGroupsGroupIdMessagesMessageIdPollsVotePost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiGroupsGroupIdMessagesMessageIdPollsVotePost$Json$Response(params: ApiGroupsGroupIdMessagesMessageIdPollsVotePost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<PollResultsDtoApiResponse>> {
    return apiGroupsGroupIdMessagesMessageIdPollsVotePost$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * Votes on a poll option.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiGroupsGroupIdMessagesMessageIdPollsVotePost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiGroupsGroupIdMessagesMessageIdPollsVotePost$Json(params: ApiGroupsGroupIdMessagesMessageIdPollsVotePost$Json$Params, context?: HttpContext): Observable<PollResultsDtoApiResponse> {
    return this.apiGroupsGroupIdMessagesMessageIdPollsVotePost$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<PollResultsDtoApiResponse>): PollResultsDtoApiResponse => r.body)
    );
  }

  /** Path part for operation `apiGroupsGroupIdMessagesMessageIdPollsVoteDelete()` */
  static readonly ApiGroupsGroupIdMessagesMessageIdPollsVoteDeletePath = '/api/groups/{groupId}/messages/{messageId}/polls/vote';

  /**
   * Removes the user's vote from a poll.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiGroupsGroupIdMessagesMessageIdPollsVoteDelete$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiGroupsGroupIdMessagesMessageIdPollsVoteDelete$Plain$Response(params: ApiGroupsGroupIdMessagesMessageIdPollsVoteDelete$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<PollResultsDtoApiResponse>> {
    return apiGroupsGroupIdMessagesMessageIdPollsVoteDelete$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * Removes the user's vote from a poll.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiGroupsGroupIdMessagesMessageIdPollsVoteDelete$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiGroupsGroupIdMessagesMessageIdPollsVoteDelete$Plain(params: ApiGroupsGroupIdMessagesMessageIdPollsVoteDelete$Plain$Params, context?: HttpContext): Observable<PollResultsDtoApiResponse> {
    return this.apiGroupsGroupIdMessagesMessageIdPollsVoteDelete$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<PollResultsDtoApiResponse>): PollResultsDtoApiResponse => r.body)
    );
  }

  /**
   * Removes the user's vote from a poll.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiGroupsGroupIdMessagesMessageIdPollsVoteDelete$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiGroupsGroupIdMessagesMessageIdPollsVoteDelete$Json$Response(params: ApiGroupsGroupIdMessagesMessageIdPollsVoteDelete$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<PollResultsDtoApiResponse>> {
    return apiGroupsGroupIdMessagesMessageIdPollsVoteDelete$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * Removes the user's vote from a poll.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiGroupsGroupIdMessagesMessageIdPollsVoteDelete$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiGroupsGroupIdMessagesMessageIdPollsVoteDelete$Json(params: ApiGroupsGroupIdMessagesMessageIdPollsVoteDelete$Json$Params, context?: HttpContext): Observable<PollResultsDtoApiResponse> {
    return this.apiGroupsGroupIdMessagesMessageIdPollsVoteDelete$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<PollResultsDtoApiResponse>): PollResultsDtoApiResponse => r.body)
    );
  }

}
