/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BooleanApiResponse } from '../../models/boolean-api-response';

export interface ApiAuthValidateResetTokenGet$Params {

/**
 * User's email
 */
  email?: string;

/**
 * Reset token
 */
  token?: string;
}

export function apiAuthValidateResetTokenGet(http: HttpClient, rootUrl: string, params?: ApiAuthValidateResetTokenGet$Params, context?: HttpContext): Observable<StrictHttpResponse<BooleanApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiAuthValidateResetTokenGet.PATH, 'get');
  if (params) {
    rb.query('email', params.email, {});
    rb.query('token', params.token, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BooleanApiResponse>;
    })
  );
}

apiAuthValidateResetTokenGet.PATH = '/api/auth/validate-reset-token';
