/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RefreshTokenDto } from '../../models/refresh-token-dto';
import { TokenDtoApiResponse } from '../../models/token-dto-api-response';

export interface ApiAuthRefreshPost$Params {
  
    /**
     * Refresh token information
     */
    body?: RefreshTokenDto
}

export function apiAuthRefreshPost(http: HttpClient, rootUrl: string, params?: ApiAuthRefreshPost$Params, context?: HttpContext): Observable<StrictHttpResponse<TokenDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiAuthRefreshPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TokenDtoApiResponse>;
    })
  );
}

apiAuthRefreshPost.PATH = '/api/auth/refresh';
