/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PasswordResetResponseDtoApiResponse } from '../../models/password-reset-response-dto-api-response';
import { ResetPasswordDto } from '../../models/reset-password-dto';

export interface ApiAuthResetPasswordPost$Params {
  
    /**
     * Reset password request
     */
    body?: ResetPasswordDto
}

export function apiAuthResetPasswordPost(http: HttpClient, rootUrl: string, params?: ApiAuthResetPasswordPost$Params, context?: HttpContext): Observable<StrictHttpResponse<PasswordResetResponseDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiAuthResetPasswordPost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PasswordResetResponseDtoApiResponse>;
    })
  );
}

apiAuthResetPasswordPost.PATH = '/api/auth/reset-password';
