/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BooleanApiResponse } from '../../models/boolean-api-response';
import { VerifySecurityCodeDto } from '../../models/verify-security-code-dto';

export interface ApiAuthVerifySecurityCodePost$Params {
  
    /**
     * Security code verification request
     */
    body?: VerifySecurityCodeDto
}

export function apiAuthVerifySecurityCodePost(http: HttpClient, rootUrl: string, params?: ApiAuthVerifySecurityCodePost$Params, context?: HttpContext): Observable<StrictHttpResponse<BooleanApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiAuthVerifySecurityCodePost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BooleanApiResponse>;
    })
  );
}

apiAuthVerifySecurityCodePost.PATH = '/api/auth/verify-security-code';
