/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ThemeDtoIEnumerableApiResponse } from '../../models/theme-dto-i-enumerable-api-response';

export interface ApiThemesGet$Plain$Params {
}

export function apiThemesGet$Plain(http: HttpClient, rootUrl: string, params?: ApiThemesGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ThemeDtoIEnumerableApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiThemesGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ThemeDtoIEnumerableApiResponse>;
    })
  );
}

apiThemesGet$Plain.PATH = '/api/Themes';
