/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ThemeDtoApiResponse } from '../../models/theme-dto-api-response';

export interface ApiThemesUsersUserIdEffectiveGet$Json$Params {

/**
 * User ID
 */
  userId: string;

/**
 * Whether the system is in dark mode (optional)
 */
  isDarkMode?: boolean;
}

export function apiThemesUsersUserIdEffectiveGet$Json(http: HttpClient, rootUrl: string, params: ApiThemesUsersUserIdEffectiveGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ThemeDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiThemesUsersUserIdEffectiveGet$Json.PATH, 'get');
  if (params) {
    rb.path('userId', params.userId, {});
    rb.query('isDarkMode', params.isDarkMode, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ThemeDtoApiResponse>;
    })
  );
}

apiThemesUsersUserIdEffectiveGet$Json.PATH = '/api/Themes/users/{userId}/effective';
