/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateThemeSyncDto } from '../../models/update-theme-sync-dto';
import { UserThemeDtoApiResponse } from '../../models/user-theme-dto-api-response';

export interface ApiThemesUsersUserIdSyncPut$Plain$Params {

/**
 * User ID
 */
  userId: string;
  
    /**
     * Updated sync preference
     */
    body?: UpdateThemeSyncDto
}

export function apiThemesUsersUserIdSyncPut$Plain(http: HttpClient, rootUrl: string, params: ApiThemesUsersUserIdSyncPut$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<UserThemeDtoApiResponse>> {
  const rb = new RequestBuilder(rootUrl, apiThemesUsersUserIdSyncPut$Plain.PATH, 'put');
  if (params) {
    rb.path('userId', params.userId, {});
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserThemeDtoApiResponse>;
    })
  );
}

apiThemesUsersUserIdSyncPut$Plain.PATH = '/api/Themes/users/{userId}/sync';
